### ISSUE TITLE
NSB light efficiency - what are the actual units?

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#1080]
`validate_camera_efficiency` generates different plots, among them the NSB light efficiency, see below:

<img width="566" alt="Screenshot 2024-07-17 at 13 20 08" src="https://github.com/user-attachments/assets/f1ed9552-b19e-4e5c-8b3d-7f205c50cd7f">

The values are >1 on the y-axis, so they are not an efficiency. What are they? Units attached? This should be clarified.

**Comment by orelgueta** [comment]
For NSB this is not efficiency, it is the differential photon rate in the units: `10^9 ph/ (nm s m^2 sr)`. I will assign myself to fix it soon.
