### ISSUE TITLE
Remove simtools/applications/db_development_tools/add_new_parameter_to_db.py and mark_non_optics_parameters_non_applicable.py?

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#1094]
Suggest to remove this applications, as there is no use case anymore for it (object if you think there is).

Model parameters should be updated/added through merge request using the model parameter repository and not directly using this application. Using this will lead to the possible loss of the updated data (as we see now the repository as the ‘ground truth’ and the database entries as copies of the repository).

mark_non_optics_parameters_non_applicable.py is a bit of a hack and easy to replace when needed again. At this point, it raises maintenance questions.

**Comment by GernotMaier** [comment]
@orelgueta - can you comment on those applications? We have replace all this and add now values to the DB only from the repository, but never directly. I would like to remove the code (less code == less maintenance).

**Comment by orelgueta** [comment]
Sure, those can be removed. I don't think they should have been there at all, they were written for me to take care of the DB,  not to be included in the repo.

(Apologies for not responding quicker, I still haven't cleaned up my simtools inbox after coming back and these direct mentions got "buried" under ~1000 e-mails.)
