### ISSUE TITLE
validate_file_using_schema.py is incredibly slow

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#1104]
Stunning how slow the CI on gitlab is: e.g. https://gitlab.cta-observatory.org/cta-science/simulations/simulation-model/model_parameters/-/jobs/216303 

This loops over all json files in the model (2140 files) and it takes 30-50 min!!  If would be 1 min using bash, this needs investigation.

**Comment by orelgueta** [comment]
I don't think #1118 actually solves this issue, so I am reopening this issue.
