### ISSUE TITLE
pylint ignore in toml file?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#1105]
https://github.com/gammasim/simtools/blob/07c5658da0dc088bb0d5b28b2e6d0f7129f0525f/pyproject.toml#L132

Should this really be in the toml file rather than in the local vscode settings?

**Comment by GernotMaier** [comment]
This is not astropy specific, but for pylint. 

Switching it off e.g., gives you:

```
 pylint simtools/applications/validate_cumulative_psf.py
************* Module simtools.applications.validate_cumulative_psf
simtools/applications/validate_cumulative_psf.py:152:52: E1101: Module 'astropy.units' has no 'km' member; maybe 'cm'? (no-member)
simtools/applications/validate_cumulative_psf.py:153:43: E1101: Module 'astropy.units' has no 'deg' member; maybe 'dex'? (no-member)
simtools/applications/validate_cumulative_psf.py:154:30: E1101: Module 'astropy.units' has no 'deg' member; maybe 'dex'? (no-member)
```

I've added a comment to the pyproject.toml file, see PR #1111

**Comment by orelgueta** [comment]
I assume you mean 

> This is not ~~astropy~~ **vscode** specific, but for pylint.

In that case, all good. The comment with the SO URL confused me (and I see that issue in my vscode as well).
