### ISSUE TITLE
PrimaryParticle doesn't validate consistency of arguments

### ISSUE THREAD

**Issue by maxnoe** [gammasim/simtools#1126]
```
>>> PrimaryParticle(corsika7_id=5, pdg_id=-12)
<simtools.corsika.primary_particle.PrimaryParticle object at 0x7fac3564cb10>
```

the correct pdg_id for the mu+ is -13.

**Comment by GernotMaier** [comment]
This is a bad API design - the intention is that you declare PrimaryParticle with either the corsika_id or the pdg_id or the name. I will change this.

**Comment by maxnoe** [comment]
I think it is in general bad design to have a constructor that takes mutually exclusive arguments.

A better pattern would be to have the constructor take only one argument and have alternative constructors for the other options, e.g.:

```
PARTICLE_NAMES_TO_PDGID = {
    "gamma": Particle.from_name("gamma").pdgid,
    "proton": Particle.from_nucleus_info(a=1, z=1).pdgid,
...
}


class PrimaryParticle:
    def __init__(self, pdg_id):
        self.particle = Particle.from_pdgid(pdg_id)

   @classmethod
   def from_corsika7_id(cls, corsika7_id):
        pdg_id = Corsika7ID(corsika7_id).to_pdgid()
        return cls(pdg_id)

    def from_name(cls, name):
        ...
```
