### ISSUE TITLE
Production tool seems broken

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#1129]
Running the production tool reports a successful run but no simulation is actually performed. I didn't look into it deeply yet, but at minimum I noticed so far that
- no telescopes are actually defined in CORSIKA. 
- There's an error due to zeroth telescope line below:
https://github.com/gammasim/simtools/blob/6484aa889c5fa196ecf6e7ec871c7ec568afeeee/simtools/simtel/simtel_config_writer.py#L179
- The names of the submission scripts contain None.
- etc.

I will try to fix these issues soon, but I thought I should open this issue already to make sure everyone is aware.

P.S.
I discovered these issues because I am writing an integration test that will discover such cases, so at least we should be covered in the future.

**Comment by orelgueta** [comment]
> * no telescopes are actually defined in CORSIKA.
> * There's an error due to zeroth telescope line below:
>   https://github.com/gammasim/simtools/blob/6484aa889c5fa196ecf6e7ec871c7ec568afeeee/simtools/simtel/simtel_config_writer.py#L179
> * The names of the submission scripts contain None.

These were solved, new issues were found in the meantime.

**Comment by GernotMaier** [comment]
Not surprised that not everything works as expected after the large refactoring - but surprised that no simulations are performed. This is puzzling, as I recently changed the number of events to be simulated in the integration tests for `simulate_prod` and the execution time changed significantly.

**Comment by orelgueta** [comment]
Yes for the user input provided in the tests the simulation runs. When I ran with different user input which is supposed to be valid (and raises no errors), no simulation ran. I tried to fix that now and make sure the user input is better validated.

There are other issues in the configuration I am working on but either way this issue will be resolved soon.
