### ISSUE TITLE
Fix warning MissingReferenceMetadata when running unit test `tests/unit_tests/simtel/test_simulator_light_emission.py::test_plot_simtel_ctapipe`

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#1168]
`pytest --no-cov tests/unit_tests/simtel/test_simulator_light_emission.py::test_plot_simtel_ctapipe` gives the following warning:

```
/Users/maierg/micromamba/envs/simtools-dev/lib/python3.11/site-packages/ctapipe/core/provenance.py:332: MissingReferenceMetadata: Could not read reference metadata for input file: /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim-tools/simtools/tests/resources/xyzls_layout.simtel.gz
```

This should be fixed.

**Comment by maxnoe** [comment]
I think this is as much an issue for ctapipe as here.

At the moment, we *know* that we cannot expect this metadata in simtel files, so ctapipe shouldn't warn about it.

In the long-term, simpipe should make sure that the required CTAO reference metadata is stored, by using the simtel metaparams system and ctapipe should read it.

I opened a PR in ctapipe to silence this warning for now here:
https://github.com/cta-observatory/ctapipe/pull/2644

**Comment by GernotMaier** [comment]
Yes, we can close this.
