### ISSUE TITLE
Suggestion to improve retrieving the list of available array elements from the database

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#1176]
The list of available array elements in the DB is accessed during the definition phase for site, all calibration devices and all telescopes. Multiple identical queries are obviously not efficient.

Suggestion to solve this:

Add a new module db.db_array_elements with the following functions:

```
@cached
get_available_array_elements(model_version, collection, db_config)
```

- `@cached` means that this function is calling the DB only once for the given parameters
- removes current bug of returning the wrong list of array elements when e.g., called first with ‘telescope’ and then with ‘calibration_devices’ as collections

Would move the other array element functions also in this module (get_available_array_elements_of_type, get_array_element_list_for_db_query). This removes some code from the very long db_handler module (which is good).

@orelgueta - as we discussed the problem, would that be a good solution?

**Comment by orelgueta** [comment]
Sure, I don't have any objections. However, if it is a separate model, I assume you will also separate the part opening the connection to a third module? This would allow us to still use a "singleton" for setting up the connection (not a real one, but never mind). We can discuss in depth in person again tomorrow.

**Comment by GernotMaier** [comment]
I think we change the call to

```
@cached
get_available_array_elements(model_version, collection, db)
```

where `db` points to an existing instance of the db_handler.
