### ISSUE TITLE
test_commandline_tools in CI-Integration tests fails when adding new applications

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#1229]
This is an issue related to failing CI-integration tests when adding new applications.

The failure is due to the usage for the simtools-prod container, which has not been updated yet during a pull request and therefore does not include the new application.

Not sure what the best solutions are:

- run this test as an additional step in the docker container generation CI ([build-docker-images.yml](.github/workflows/build-docker-images.yml)
- run this test only for merge-to-main (after the CI docker generation)
- drop the test? I am not sure actually what we are testing? We ensure that the applications defined in pyproject.toml exist? That should always be the case, otherwise `pip install` would not work (which we test in `testbuilding` in the same workflow).

Any input?

**Comment by GernotMaier** [comment]
Second point would be to first build the docker container, and then run the test using the newly build docking container. This would make sure that the new applications are available.

**Comment by orelgueta** [comment]
If there's an an easy way to technically achieve the second point, then I vote for it. Otherwise, option one looks fine as well.
