### ISSUE TITLE
Warnings from corsika_autoinputs on using `--keep-seeds`

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#1288]
Running

```
python src/simtools/applications/simulate_prod.py --config tests/integration_tests/config/simulate_prod_gamma_diffuse_20_deg_North_check_output.yml
```

prints out the following warning:

```
WARNING::corsika_runner(l202)::_get_autoinputs_command::Using --keep-seeds option in corsika_autoinputs is not recommended. It should only be used for testing purposes.
```

This should be fixed, we don't want any warnings (unless they are justified).

**Comment by orelgueta** [comment]
The warning is justified. One should almost never use `--keep-seeds`. The only exception is for testing purposes, which is how it is used here. So in my opinion, both things are correct, the warning and the usage. Therefore, I don't think we should change anything.

**Comment by GernotMaier** [comment]
Do we use those seeds anywhere in the tests? How is it different to run it without those seeds.

**Comment by orelgueta** [comment]
Yes, we use fixed seeds in these tests because otherwise the variation in the output would be too large for the small amount of events we generate. We could remove it, but then we would need to increase the number of showers to ~100.

**Comment by GernotMaier** [comment]
Great, thanks. Makes sense. I guess we can close this issue then.
