### ISSUE TITLE
Add functionality to retrieve gammasim-tools version

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#223]
Software version is hardwired into simtools/version.py

This should be improved in future, see e.g.. the [ctapipe approach](https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/version.py)

**Comment by GernotMaier** [comment]
Would be nice to have this one solved - not relevant but simply important to have.

As we are now using setup tools, we should be able to use the solution indicated in  https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/version.py

**Comment by orelgueta** [comment]
Coincidentally, the same was implemented just now in [this PR](https://github.com/cta-observatory/pycorsikaio/pull/17) in corsikaio. Maybe it can be used as an example.

**Comment by GernotMaier** [comment]
I've looked into it and it is too complicated for me. Maybe we can ask Max to add it? Or does one of you get familiar with setuptools?
