### ISSUE TITLE
Write telarray_rand.conf.used into output directory

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#274]
This file is currently written into the simtools root directory by sim_telarray. 

Suggest to add a cleanup stage for classes using sim_telarray to move this into the output directory.

**Comment by GernotMaier** [comment]
Had a look into this issue (which is not such an important issue): the many telarray_rand.conf.used files are produced when running integration tests and almost each time sim_telarray is called (e.g., for tune_psf). `telarray_rand.conf.used` are not overwritten, but the second file contains the process ID (e.g., `telarray_rand.conf.used-2635`) .

To solve this requires actually a few more changes, including probably the (recommended) migration from `os.system` to `subprocess.call()` or `subprocess.Popen` (we sometimes use subprocess, and sometimes use os.system).

This is maybe something to do for the future and unrelated to the telarray_rand.conf files: have a core service class doing the handling of the system calls, taking care of crashed jobs, stderr, and files produced we don't want to keep.

**Comment by GernotMaier** [comment]
This is not an issue anymore, although I can’t remember how it was fixed. 

I haven’t seen any telarray_rand.conf.used file since a long time ago.

Marked as ‘Close this’ - please object if you think this is still relevant.

**Comment by orelgueta** [comment]
This was fixed in #736. We still get one file I think, but one file is not a real issue so I am closing this issue.
