### ISSUE TITLE
applications/plot_simtel_histograms fails reading sim_telarray histogram file

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#277]
Running plot_simtel_histograms on the example files in `tests/resources/gamma_20deg_0deg_run1___cta-prod5-lapalma_desert-2158m-LaPalma-dark.hdata.zst` fails.

```
python applications/plot_simtel_histograms.py -l tt.list  -o ../histo
```
using 
```
cat tt.list
tests/resources/gamma_20deg_0deg_run1___cta-prod5-lapalma_desert-2158m-LaPalma-dark.hdata.zst
```
The error is:
```
 python applications/plot_simtel_histograms.py -l tt.list  -o ../histo
INFO::base(l60)::__init__::Opening new file tests/resources/gamma_20deg_0deg_run1___cta-prod5-lapalma_desert-2158m-LaPalma-dark.hdata.zst
INFO::base(l93)::__init__::Found zstd compressed file
WARNING::simtel_histograms(l104)::_combineHistogramFiles::Problematic file tests/resources/gamma_20deg_0deg_run1___cta-prod5-lapalma_desert-2158m-LaPalma-dark.hdata.zst (cannot read negative amounts less than -1)
```

Need also to improve the exception handling to print out a more detailed error message (this is probably an exception raised in pyeventio?).

**Comment by GernotMaier** [comment]
@VictorBarbosaMartins - is this issue still an issue? I think you have addressed this with the recent updates.

**Comment by VictorBarbosaMartins** [comment]
Hi @GernotMaier, yes this shouldnt be an issue anymore (outdated). I am then closing it.
