### ISSUE TITLE
Review contents of corsika_parameters.yml and proceed using DB

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#306]
The production application applications/production.py uses as input corsika parameters defined in  [corsika_parameters.yml](https://github.com/gammasim/gammasim-tools/blob/master/data/corsika/corsika_parameters.yml).

This includes:
1. corsika-related parameters like interaction flags
2. telescope positions
3. site parameters (like altitude, magnetic field parameters)

Telescope positions and site parameters are part of the MC model and should use the corresponding values from the DB. I think the values already now disagree a bit from what we have in the models. We also might consider moving the corsika-related default parameters to the DB.

Suggested first steps:
- read site parameters from DB for the given site (requires to somewhere state the model version; possible in the production configuration file)
- read telescope positions from DB (same as for site parameters)

**Comment by orelgueta** [comment]
Victor and I discussed this exact thing this morning and decided to start from a yaml file (which apparently already exists) and then insert to the DB all of these parameters. I think we can open a specific collection for CORSIKA as well and add to it the CORSIKA-related parameters. The rest I agree with.

**Comment by GernotMaier** [comment]
Which yaml file do you mean?

**Comment by orelgueta** [comment]
This one - [corsika_parameters.yml](https://github.com/gammasim/gammasim-tools/blob/master/data/corsika/corsika_parameters.yml). Yesterday I suggested to Victor to write such a yaml file and apparently it already exists.

**Comment by GernotMaier** [comment]
Note that this issue is partly addressed in PR #761 :

- all site-related parameters has been removed and are now pull from the database

**Comment by GernotMaier** [comment]
Note that this issue is partly addressed in PR #1037 

- primary particles are now defined in the PrimaryParticle class (and using the scikit-hep/particle package)
