### ISSUE TITLE
Flexibilize array layout names (names.allLayoutArrayNames) to allow simulation of user-defined array

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#361]
To use the atmosphere tool (#360) we need to generate a "fake" array of telescopes covering up a large area on the ground. This is in the current version of the code not possible. Only a handful of arrays are possible, with pre-defined array configuration:
https://github.com/gammasim/gammasim-tools/blob/67fd2e3e6d347e415b42e1dcb029501a996388c9/simtools/util/names.py#L426-L435

We need to make it more flexible and allow a user-defined array, or more specifically, we need to allow the user to input a telescope-list file into the corsika config file instead of always linking to pre-defined options. This is important now for the atmosphere tool but could also be important in the future to study different arrays, for instance, upgrades of the current CTA layout or eventually for the broader community.

**Comment by GernotMaier** [comment]
PR #947  is addressing this: layouts given through ecsv files are not constraint in their naming anymore. This issue will therefore close with merging of #947.
