### ISSUE TITLE
Change "Current" to "Released"

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#416]
Change the name "Current" version to "Released" to make the meaning clearer.

**Comment by GernotMaier** [comment]
I guess this means the `Current` flag in e.g.,  `pars = db.get_site_parameters("North", "Current")` ?

**Comment by orelgueta** [comment]
Yes, this was essentially your suggestion. It is unfortunately fairly low in the to-do list so was never done but maybe in the next scheduled "maintenance period".
