### ISSUE TITLE
Unused parameter in corsika_runner

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#417]
https://github.com/gammasim/gammasim-tools/blob/8cdb37a97cf9c4fcf37ed0380927c28e4735cb3a/simtools/corsika/corsika_runner.py#L84

This parameter is set in the simulator, but is not actually used anywhere in the CORSIKA runner. It's seems weird to simply remove it. Any ideas @GernotMaier?

**Comment by GernotMaier** [comment]
`CorsikaConfig` has an option to load CORSIKA parameters from a yaml file, but this is not set in corsika_runner. 

This needs a bit more investigation to understand better if we want that option or not (if not, than we should remove the code consistently also in corsikaconfig. 

I assigned the issue to myself and will look into it.

**Comment by GernotMaier** [comment]
`corsika_parameters_file` is used (implemented in one of the merge request listed above). I therefore close this issue.
