### ISSUE TITLE
"Applications" should be provided as entry points

### ISSUE THREAD

**Issue by maxnoe** [gammasim/simtools#423]
That makes them independent of being in the repository and enables installing `gammasim-tools` as a python package without downloading the git repository.

For this, the applications directory should be moved into the `simtools` (why no gamma there?) package and be configured as `console_scripts` entry points, e.g. like here:

https://github.com/cta-observatory/ctapipe/blob/f789773f94bc5f33b33258dab13b5d4bd6c467dd/setup.cfg#L85-L89

**Comment by GernotMaier** [comment]
Console scripts with consistent naming (all applications start with `simtools-…`) are introduced with PR #465
