### ISSUE TITLE
Requirements for the python package are missing

### ISSUE THREAD

**Issue by maxnoe** [gammasim/simtools#424]
The project only provides a conda `environment.yml`, however, this does not specify the dependencies of a python package, it describes a conda environment.

The actual requirements of the package have to be specificied in `setup.cfg` or `pyproject.toml`, see:
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#declaring-required-dependency

**Comment by GernotMaier** [comment]
Requirements and dependencies are listed in the new pyproject.toml file, see PR #465 .
