### ISSUE TITLE
LayoutArray

### ISSUE THREAD

**Issue by maxnoe** [gammasim/simtools#428]
The LayoutArray (why the strange order name?) has `add_telescope` which uses `xx`, `yy` and `corsika_z`. 

However, other parts of the documentation note that the goal is to be disentangled as much as possible from the simulation software.

So why not specify the real z coordinate and then compute the value needed for CORSIKA in the code path dealing specifically with CORSIKA?

**Comment by maxnoe** [comment]
Also: xx and yy do not provide any further information over just using x and y, it just looks weird.

**Comment by GernotMaier** [comment]
Forgot about this one, sorry @maxnoe 

The logic is that `telescope_position` handles all relevant coordinate systems (UTM, mercator, CORSIKA) and this is the only place in the code where we do transformation of spatial coordinates. Don't think we really introduce a dependence, I would call it an option to use CORSIKA coordinates (as `add_telescope(self, telescope_name, crs_name, xx, yy, altitude=None, tel_corsika_z=None)` allows to use either altitude or corsika_z)

For xx, yy, zz: probably the original thought was to distinguish it from x, y, z (is it can be long, lat, altitude). I'll change it to x, y, z if this is clearer.

**Comment by GernotMaier** [comment]
I remember now why `xx` etc is used: we are using the pyproj package for transformation, and this is the convention for variable naming there (e.g., see https://pyproj4.github.io/pyproj/stable/api/transformer.html#pyproj.transformer.Transformer.transform)

So I think this is fine and well motivated.

**Comment by GernotMaier** [comment]
Closing this issue, as I think the naming question has been addressed and using the convention from pyproj is well motivated.

**Comment by maxnoe** [comment]
> The logic is that telescope_position handles all relevant coordinate systems

Then I'd expect an `ArrayLayout` to be a collection of `TelescopePosition` s

**Comment by GernotMaier** [comment]
It is kind of: `LayoutArray._telescope_list` contains all `TelescopePositions`s .

(and I agree on the naming, don't remember why we called it LayoutArray)
