### ISSUE TITLE
Write simulation output and results into DB

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#43]
It would be good to start already writing all output and results when running simulations into the DB. It probably won't be used for now, but it's good to have the experience of it.

Note that this is would result in many changes to the code everywhere, so perhaps later this issue will be broken up to smaller pieces.

**Comment by GernotMaier** [comment]
I think we need to clarify how we want to save the output of simtools.

Model parameters include the relevant provenance / metadata should go into the model parameter database.

All other associated data products (which might be quite a few - plots, derived data, ...) should be digested by BDMS. 

Require also input from DPPS on the general data archiving / usage of BDMS and database and a write up of specifications.

**Comment by GernotMaier** [comment]
I suggest to close this issue. Don't expect that we use the DB to write actual simulation output. The additional applications of the DB (e.g., configuration database, production DB) are discussed elsewhere.

My assumption is that output is saved through BDMS (which needs to be specified better as soon as we know more about BDMS).

**Comment by orelgueta** [comment]
Yes we can close this. It's a bigger topic than this issue anyway and there's no "danger" of it being forgotten.
