### ISSUE TITLE
Add pylint as prehook (define pylint.rc)

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#431]
Add a pre-commit hook for pylint.

Suggestions (from PR #430) on settings:
- `W1203` - Use lazy % formatting in logging functions
- `C0103` - Variable name "..." doesn't conform to snake_case naming style
- `E0401` - unable to import '...'
- `R0902` - Too many instance attributes
- `R0913` - Too many arguments
- `R0914` - Too many local variables

(these should be defined in a pylintrc file)

**Comment by GernotMaier** [comment]
Why do you want to ignore `C0130`? is this mostly because of common short variables? If it is that, maybe we can add a list to pylintrc using `good-names` (https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#good-names)

**Comment by orelgueta** [comment]
Yes, we could add a list of good-names. It would be quite a few and some of them would be quite specific, but perhaps it's best to change some variable names in the code and then add a list of `good-names` for the others. I suggest we don't ignore `C0130` in the first instance and I will try to fix it later.
