### ISSUE TITLE
read site from telescope file in print_array_elements

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#436]
We would like to change print_array_elements to read the site from the telescope file and not put it by hand. For that we will need to use `read_telescope_file` function before initializing the class and get the site from the metadata. In addition to that we would like to change the metadata in the header of telescope files to show only the site and not all the site information. The site information needs to be in the DB only.
    
    Good question. This is not the best solution. It would be better to get the site directly from the file (given by `args_dict["array_element_list"]`) that is anyways used in the line below this one. To do that we would have to read the file before initializing the class, therefore, I changed the code now and divided the `read_telescope_list_file` into two files: `read_telescope_list_file` (now static method, i.e. one can use without initializing the class) and `initialize_layout_array_from_telescope_file` which does exactly what `read_telescope_list_file` was doing before. With this we are able to implement a function that reads the metadata from the telescope file and give us the site, then we initialize the class. Nevertheless, in discussions with Orel we realized that we want to drastically reduce the metadata in the telescope file and instead of passing all the coordinates info, we simply pass the site and then the rest of the information is read from the DB. Since we will probably implement that later, I suggest we keep this "North" here and open an issue so we dont forget it.

_Originally posted by @VictorBarbosaMartins in https://github.com/gammasim/gammasim-tools/pull/429#discussion_r1049493274_

**Comment by orelgueta** [comment]
I think this issue should be somewhat different. What we should do is allow to either set the `corsika_obs_level` explicitly in the file like it is done now, e.g., in `telescope_positions-South-4MST.ecsv` we have
```
#   corsika_obs_level: !astropy.units.Quantity
#     unit: *id001
#     value: 2147.0
```

or to set in the file the site and then set the `corsika_obs_level` accordingly from the DB. It should be a simple check added to `_initialize_corsika_telescope_from_dict`.

**Comment by VictorBarbosaMartins** [comment]
I agree that this issue has to change, since Gernot argued in #429 for keeping all the info in the headers. In this case I am in favor of adding the site to the header as well, instead of reading from the DB and matching the site altitude.

**Comment by orelgueta** [comment]
Not instead, in addition. That is, allow both options. Providing all info in the file or just the site name.

**Comment by VictorBarbosaMartins** [comment]
as far as I understood from the discussions in #429 (and offline) before, we always want to have all the site information in the header of the telescope files. Isn't it the case @GernotMaier ?

**Comment by GernotMaier** [comment]
I would like to re-assign this issue to myself - @VictorBarbosaMartins ok with this?

What I want to do:

- the metadata associated with a telescope position file should clearly identify the associated site and validity range.
- this should be sufficient to retrieve all other parameters from the model parameter database

**Comment by VictorBarbosaMartins** [comment]
Yes, please go ahead @GernotMaier

**Comment by GernotMaier** [comment]
This issue can be closed (probably since a while):

- no site is required anymore on the command line
- information is read from the metadata header or from the (new) json `site` parameter
