### ISSUE TITLE
Set output directory for data products from applications.

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#463]
Output path for data products from applications requires knowledge of the full logic of how these directories are created. 

I suggest that when the user gives as a configuration option `--output_path`, all files are written into this directory and no subdirectories are created.

This is the issue:
e.g., when running `print_array_elements.py`, the converted coordinate file is written to currently `./tmp/simtools-output/d-2023-06-18/layout/telescope_positions-corsika.ecsv`, when providing `--output_path ./tmp/` . Including dates in a non-standard format (`d-2023`) does make it even more difficult.

Solution:
Suggest at least that when `output_path` is given, that the files are written directly into this directory. We could also discuss if one could give explicitly the name of the output file(s).

**Comment by orelgueta** [comment]
As mentioned when we talked, I think it's clear that if a user provides an `output_path`, that should be the exact output path without any additions/omissions.
