### ISSUE TITLE
Check usage of zstd in corsika_runner.py and simtel_runner_array

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#469]
Check if it requires the python package zstd or a runtime library.

**Comment by orelgueta** [comment]
We have the `zstandard` as a python dependency so it's installed as a package in python. However, we need it available as a runtime library (well sim_telarray needs it when using the zst compression). Installing as a dependency with pip does not provide zstd (or does not add it to the path, not sure). Therefore, I added zstd to the packages installed in the containers. It takes just 1.5 MB so it should be fine and probably not worth checking if we can get it from `zstandard`.

**Comment by GernotMaier** [comment]
OK! I think this clarifies this and we can close this issue.
