### ISSUE TITLE
Rethinking workflow description module 

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#491]
Would like to discuss the current implementation of [simtools/data_model/workflow_description.py](https://github.com/gammasim/simtools/blob/4d30df5ddf1aa790add92673b0d81077f0439f7b/simtools/data_model/workflow_description.py). I suggest to simplify and rename, as we are using now [workflows in cwl](https://github.com/gammasim/workflows) (which we didn't know about at the time this module was written).

The current implementation uses generally a workflow configuration file (example is [tests/resources/set_MST_mirror_2f_measurements_from_external.config.yml](https://github.com/gammasim/simtools/blob/4d30df5ddf1aa790add92673b0d81077f0439f7b/tests/resources/set_MST_mirror_2f_measurements_from_external.config.yml). 

It currently does:
1. prepare activity context (product name; issues uuid)
2. collects metadata from different sources (command line, input meta and data files; workflow configuration file)
3. allows to set `input_meta` and `input_data` as well as activity names
4. reads in schema used for the validation of the input data (hmm, this seems to be out of place)

The cwl workflows will take over inputs and outputs (3). Schemas for validation (4) should not be in the workflow_description. I suggest to remove both items from workflow_descriptions.

This means we end with a simpler module which collects and enriches meta data when running an application. This is fine and we need that - only that I suggest to rename workflow_description.py to meta_data_collector. 

Comments please. @orelgueta @VictorBarbosaMartins

**Comment by VictorBarbosaMartins** [comment]
Hi @GernotMaier. I am not very used to this module, but it seems like a good idea to adapt it, since we now decided to go with workflow language. 

Where would you suggest to move (4) to? Alternatively, we could keep it there and call the module `meta_data_handler` and have everything related to meta data together.

**Comment by GernotMaier** [comment]
There is  a kind of standard for schema (https://json-schema.org/) and tools available. I think we should move towards this and use available libraries for most of the functionality of 4. We did this already for the parameter definition files (outside of simtools).

**Comment by orelgueta** [comment]
I agree with your suggestion. It would be nice to use existing libraries for what is possible and changing this module to be just a `metadata_collector` (notice metadata in one word).

**Comment by GernotMaier** [comment]
@orel - we have a [meta_data_model.py](https://github.com/gammasim/simtools/blob/main/simtools/data_model/meta_data_model.py)!

After looking around a bit and see what people generally do, I suggest to rename it to `metadata_model` and use `metadata_collector`.

**Comment by orelgueta** [comment]
Agree, metadata is one word.
