### ISSUE TITLE
Add calls to command line tools (e.g, simtools-print-array-elements)

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#498]
To test the usage of applications from the user's view, I suggest to add to the integration test a couple of lines to call all applications as well as with their command line tool name. 

All try to have this as argument, so that it is running in parallel (as integration already now take 20-30 min).

Any objections / suggestions?

**Comment by orelgueta** [comment]
If it doesn't make the tests longer, I have no objections.
