### ISSUE TITLE
Integration tests write out files to local directory

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#504]
The integration tests write out the following files to the local directory
- `mirror_CTA-S-LST_v2020-04-07.dat`
- `PSFcurve_data_v2.txt`
- `ray-tracing-North-LST-1-d10.0-za20.0_validate_optics.ecsv`

That is not ideal and should be fixed (files should be written to the test directory).

**Comment by GernotMaier** [comment]
Successful tests shouldn't leave any files left, is there an easy way to clean this up (or write them into a tmp directory)?

**Comment by orelgueta** [comment]
I want to write them to the temp directory but I haven't looked at it at all so I don't know yet which test produces them and why. I just noticed they are produced and didn't want to forget to fix it later.

**Comment by VictorBarbosaMartins** [comment]
This is happening also for `plot_layout_array` and `generate_corsika_histograms`, which write the outputs to `simtools-output` and do not delete them after the tests. If you find a good solution, I will be happy to apply it to these two applications as well.

**Comment by orelgueta** [comment]
This actually happens for almost all integration tests, where they wrote the output to `simtools-output`. I fixed it now in #552. In the future, please remember to provide the appropriate output path if you write new integration tests.
