### ISSUE TITLE
corsika_output module writes pngs into current path

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#507]
It looks like corsika_output is writing figures always into the current path and ignores and settings of `output_path`. This should be changed.

(affects also unittests, which for now write many histograms into the local directory).

**Comment by orelgueta** [comment]
This is also mentioned in the open PR here https://github.com/gammasim/simtools/pull/492#discussion_r1273247490 and here https://github.com/gammasim/simtools/pull/492#issuecomment-1649882644 and specifically the unittest histogram issue was discussed in mattermost. The PR already solves the latter, hopefully the other issues can be solved quickly in the same PR.

**Comment by GernotMaier** [comment]
(I knew we discussed this, but couldn't find it)

**Comment by VictorBarbosaMartins** [comment]
Closed by #492
