### ISSUE TITLE
Test of Insert files to DB issue

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#512]
I need some input on how to deal with the current DB issue since it requires taking a decision. First I will describe the test:
- One of the tests, `test_insert_files_db`, tests the function which inserts a file to the DB. 
- The test inserts a test file to the sandbox DB and checks that it is there.
- pytest then drops the entire "collection" of files in the sandbox DB so that we do not accumulate "junk".

The issue is the following:
- When we test various versions of python in the CI simultaneously, each pytest instance inserts a different test file into the sandbox DB.
- When pytest finishes it drops the **entire** collection of files in the sandbox DB. That means it drops also the files of the other tests for the other python versions currently running.
- Then the second part of the test fails because it can't find the file it inserted.
- We cannot use a random DB for this test because the API user we are using for accessing our MongoDB instance does not have permissions to drop an entire DB (rightly so). 
- Assuming we do not want to collect junk just for this test, we need to find a different solution.

Possible solutions:
- Easiest - don't test inserting files to the DB. Not ideal because the `insert_file_to_db` method is quite central in simtools, but it's also fairly simple so it's not a big deal.
- Second easiest - make an exception if we get a `None` when we try to read the file we inserted. This should solve the issue when we run simultaneous tests in the CI, but will keep the original functionality of the test when running locally as developing (I vote for this solution for now).
- We could try using [mongomock](https://github.com/mongomock/mongomock) to mock the MongoDB instance we have just for this instance. This might be the best solution in the long run, but requires a bit of time to figure it out and implement (and there's no guarantee this would actually work since gridfs is not a basic MongoDB functionality). If we vote for this I suggest we implement it only for this test and not as a general way to test our `db_handler` because it's always better to test the real DB when possible in my opinion.
- Remove the matrix in the CI and test only one python version for now (or forever).

Thoughts @GernotMaier, @VictorBarbosaMartins?

**Comment by orelgueta** [comment]
OK there's one more solution which is actually the best I think. We create a special sandbox DB for each pytest instance and empty it after the run. I thought it stays there forever until we manually remove it but apparently MongoDB drops an empty DB automatically. If this indeed works then #513 will close this issue.

**Comment by GernotMaier** [comment]
Really difficult.

The cleanest would be using the mock feature - as we want to test our code and not the database. But I see the disadvantage (having to learn how it works, another dependency).

I agree that your second point would be best. But I also see that #513 is working, so I stop answering...

**Comment by orelgueta** [comment]
Yes, tests worked, let's merge and keep an eye for the future. Glad I tested this random idea I had before implementing something more complicated...
