### ISSUE TITLE
Repository organisation

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#516]
This issue is to discuss the organisation of the gammasim repositories and includes a suggestion to merge different repositories.

As a reminder, the simulation pipeline consists of five main components:
- simulation software (like CORSIKA, sim_telarray); not considered here
- simtools - the python library with applications to setup productions, derive parameters, etc
- workflows - binding several simtools together (e.g. for model parameters the assert - derive - validate - review workflow; [early example](https://github.com/gammasim/workflows/blob/prototype-DeriveArrayElementCoordinates/workflows/DeriveArrayElementCoordinates.cwl))
- schemas - describing input data for the simulation pipelines  (e.g., [this one](https://github.com/gammasim/workflows/blob/prototype-DeriveArrayElementCoordinates/schemas/array_coordinates.schema.yml))
- docker files for production and development (see [here](https://github.com/gammasim/containers))

Having these items in three different repositories appeared kind of logical when we started. It was partly motivated to experiment with technologies new to us (e.g., docker, or now the CWL stuff).

It however generates a couple of issues:

- containers generation is not triggered by a simtools pull request or releases. They are triggered by hand: this is not nice; especially when the most recent simtools is required in containers for development.
- unit and integration tests need files across the repository (e.g., to test the simtool `validate_schema_files.py`, we need the [json schema](https://github.com/gammasim/workflows/blob/prototype-DeriveArrayElementCoordinates/schemas/jsonschema.yml); additional some files in [tests/resources](tests/resources) are duplication of files from other repositories.

My suggest therefore is to merge docker and schemas into simtools. We wait with the CWL workflows until we are convinced that this is the solution to go ahead and we make the step beyond playing around with cwl.

Suggestion:
- add a `docker` directory to simtools with the dev/prod/simtelarray/tools directory as it is now in the [containers repository](https://github.com/gammasim/containers)
- add a `schemas` directory to simtools and move the [schemas](https://github.com/gammasim/workflows/tree/prototype-DeriveArrayElementCoordinates/schemas) from the workflow repository. Note that this will be one file per model parameters (roughly 230 files) and maybe another 20-50 for the description of the input data

In case we go ahead with workflows, these would move into simtools/workflows. These will be 20-40 different workflow definitions.

This is for everyone to comment on. @orelgueta @VictorBarbosaMartins

**Comment by GernotMaier** [comment]
One point intermediate solutions (triggered by Orel's comment on the [PR in workflows](https://github.com/gammasim/workflows/pull/7#): we could simply clone the workflow repository in the simtools units and integration tests. This should be fast and would give access to all files required for testing.

**Comment by VictorBarbosaMartins** [comment]
Hi @GernotMaier, @orelgueta. I don't have a strong opinion about this, but I think it is worth here to consult with Karl and Max first, as this is a major change with implications for the future development of simtools. We can also discuss this on our meeting this week.

**Comment by GernotMaier** [comment]
I thought about this as well. But note that it is not a major re-organisation, as simtools, docker, and schema files are clearly separated in different directories.

I think we agreed now to move as a first step the docker files (see PR #532)

**Comment by GernotMaier** [comment]
I think I am happpy with the changes now and it is ok for me to leave the schema files in the workflows repository. 

Docker files have been moved and this is nice.

Main motivation to integrate the schema files is mostly the unit tests. I guess it is fine to have 1-2 copies of these files in the tests/resources directory and leave the schemas therefore in a separate repo.

Closing this. Reopen if you don't like this.
