### ISSUE TITLE
Confusing application names `simtools-production` and `simtools-simulate-prod`

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#517]
Is this actually a good naming? I am not sure what the difference is.

simtools-production: `Air shower and array simulations`

simtools-simulate-prod: `Run simulations for productions`

**Comment by orelgueta** [comment]
No these are not good names and are thought to be temporary. There's a high change I will combine the two applications into one, removing some of the functionality in `production.py` and adding some functionality to the other one. A decision will be taken in the next couple of months as `simulate-prod` continues to be developed.

**Comment by GernotMaier** [comment]
I am closing this, as we are discussing how to remove simtools-production in #660 and #910
