### ISSUE TITLE
Add a generic contact email / author for pypi

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#525]
pypi seems not to work with several authors, see https://test.pypi.org/project/gammasimtools/0.4.0.dev0/

This is a known issue, see e.g., discussions here : https://stackoverflow.com/questions/9999829/how-to-specify-multiple-authors-emails-in-setup-py.

Introduce a single generic contact point for simtools, similar to ctapipe (ctapipe-developers pointing to Karl) or gammapy (The gammapy developers pointing to gammapy-coordination-l@in2p3.fr).

We could open a list at DESY for simtools, which allows submission from non-list members. Disadvantage is that this usually leads to quite some spam.

**Comment by orelgueta** [comment]
Usually this is spam that spam filters deal with well, so I am not too worried. Also, having our e-mails listed publicly on pypi or on github is not much different I guess. I think this is the best option indeed.
