### ISSUE TITLE
Check if we can avoid using toml-to-requirements

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#536]
If I understand correctly, setuptools now supports building an editable version directly from the toml file. See for example this [SO post](https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml). Check if this can be used to remove the toml-to-requirements package and "hack" for installing using pip.

**Comment by GernotMaier** [comment]
It looks like at this point a setup.cfg/py is still needed in this case, see the [footnote](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setupcfg-caveats) in the setuptools manual.

Let's keep this issue open, probably future versions of setup tools will solve this.

**Comment by orelgueta** [comment]
Yes, that is true, a setup.py is needed, but if I understand correctly it would be a fairly simple file with just a few instructions. It would not lead to duplication. I don't mind "waiting" for future versions to provide an easier solution though.

**Comment by GernotMaier** [comment]
@orelgueta - I suggest to close this. I don't think it is a problem using the toml-to-requirements package.

**Comment by orelgueta** [comment]
OK, we can close this. Hopefully we remember to fix it once setuptools improves and allows to directly use the toml file.
