### ISSUE TITLE
Add tests that build docker images are working well

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#540]
No tests exists to ensure that the prod containers actually work (the dev container is running the integration tests). 

Add execution of integration tests on both dev and prod containers, after checking that this does not introduce a very lengthy test.

**Comment by GernotMaier** [comment]
As mentioned, `docker-dev` is tested, as it is used now for integration tests (see PR #687). This is not a direct test in a sense that errors will be only noted in upcoming pull requests. I think this is reasonable and nothing else is needed.

`docker-prod` does not contain any testing environment (no pytest; as it is a container for users). 

We could call a small set of applications (don't think we need all, maybe even only one?) after the generation of the container, e.g., 

```bash
docker run --rm -it --env-file .env \
    -v "$(pwd):/workdir/external" \
    ghcr.io/gammasim/simtools-prod:latest \
    simtools-print-array-elements \
    --input ./simtools/tests/resources/telescope_positions-North-utm.ecsv \
    --export corsika --use_corsika_telescope_height \
    --output_path /workdir/external/
```

I am hesitating a bit, as these lines look quite fine-tuned and we are still working on configuration parameters / input / etc. This would have to be kept updated (probably ok, just another thing to take care).

Maybe we start the test and then install first as part of the github action workflow pytest and run the application tests?

**Comment by VictorBarbosaMartins** [comment]
I agree that the dev docker image is already tested this way and we don't need further tests. not sure about the production docker image. It is not clear to me what should be the differences between these docker images.

**Comment by GernotMaier** [comment]
See https://gammasim.github.io/simtools/getting_started.html#docker-installation and https://gammasim.github.io/simtools/getting_started.html#docker-environment-for-developers for the two types of docker containers.

**Comment by GernotMaier** [comment]
Yes, we should make a list of applications going through the different levels of "difficulties": with/without database, with sim-telarray, writing to somewhere.

**Comment by VictorBarbosaMartins** [comment]
> Quick update:
> 
> #713 has all the changes to first build the linux image, then run the tests, then build all other images (linux/arm64/v8) and push
> 
> I would like to avoid duplication in running tests, as we would:
> 
> * run here some applications with typical configurations
> * plan to add integration tests for all applications with typical configurations
> 
> The plan is now to add to the test directory the command line parameters as yaml files. All applications can be configured by e.g., `simtools-print-array-elements --config config.yml` with `config.yml` including the command line parameters.
> 
> Example for config.yaml:
> 
> ```
> INPUT: ./tests/resources/telescope_positions-North-utm.ecsv
> EXPORT: corsika
> USE_CORSIKA_TELESCOPE_HEIGHT: True
> OUTPUT_PATH: simtools-tests
> ```
> 
> I really like this solution.
> 
> (and I notice now that this part of the code (reading from config) is broken...need to fix it first)

I also really like the idea of passing command line arguments through yaml file!
