### ISSUE TITLE
inconsistent use of `dir` and `directory` in variable names throughout the code

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#568]
Yes, this is a `directory_type` (see explanation below).

We are using both `dir` and `directory` throughout the code, so this is consistent with our naming. I suggest to open an issue to discuss if we should change this.

_Originally posted by @GernotMaier in https://github.com/gammasim/simtools/pull/565#discussion_r1303852127_

**Comment by orelgueta** [comment]
I don't think this should be changed. It is not uncommon to shorten `directory` to `dir`, as long as it is not on its own. I.e., it should be `dir_bla` or `bla_dir` and not just `dir`. The latter shouldn't exist cause it's a valid python command (and I couldn't find it anywhere by grepping). Therefore, I suggest we don't make any changes.

**Comment by VictorBarbosaMartins** [comment]
My point is the inconsistency. There are parameters which we name `something_dir`, others `something_directory`. My suggestion is to pick either one of them and stick to it.

**Comment by orelgueta** [comment]
Again, not an inconsistency I would worry about (because it is so common). I won't oppose fixing it of course, just don't think it is worth the effort.

**Comment by VictorBarbosaMartins** [comment]
I've seen PRs that were even less worth than this change, but I don't see the point to further discuss it here, therefore, I am closing the issue without changes as you suggested.
