### ISSUE TITLE
CI-integrationtests workflow run emails even with draft PR

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#573]
Hello.

**Issue**: I have realized that we receive emails of tests failing in the github actions even if the PR is on draft stage. 

**Proposed solution:** My proposal is to drop the notifications in case the PR is on draft stage. With that we would be able to use the github infrastructure and test the code during development without flooding our mail boxes. 

What do you think?
Thank you.

**Comment by orelgueta** [comment]
I don't mind it. I wonder if it's a per user setting though, rather than per project.

**Comment by GernotMaier** [comment]
I don't see any settings regarding this on the repository or on the user site. Not sure if this is possible.

**Comment by VictorBarbosaMartins** [comment]
Ok! I thought you had received emails when the tests failed in my draft PR. If that is not the case, we dont need this issue. thanks for the feedback.
