### ISSUE TITLE
Agree on what a mirror is.

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#574]
Reading code is difficult without a consistent usage of the word `mirror`.

It is e.g. difficult to understand if "True for single mirror simulations." means i) simulation of a single mirror panel; ii) simulation for a single-dish telescope; iii) simulations where the dish is seen as one single mirror. 

Suggestion for the first two cases (most important ones):

- use `mirror panel`
- use `mirror dish` (not sure here; something better?)

**Comment by GernotMaier** [comment]
Not the most important issue. Anyway:

- in most cases we mean with `mirror` a `mirror panel`
	- `config.single_mirror_mode` is identified when we simulate a single mirror panel
	- `mirror_numbers` is the number of mirror panels
	- `mirror_diameter` is the diameter of a mirror panel 

In some cases we distinguish between dual or single reflector telescopes:

- `is_two_mirror_telescope` is used to identify dual-mirror telescopes
- `mirror_class` is used (as in sim-telarray) for dual or single reflector telescopes

The `mirror` module is about simulating mirror panels.

Given that this is also an issue in sim-telarray, my feeling is the effort of introducing a consistent naming is far larger then the benefit. 

I therefore suggest to close this issue. Please protest, if you think differently.

**Comment by orelgueta** [comment]
No objection, closing.
