### ISSUE TITLE
Naming of Environmental Variables

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#583]
It's convention to have these prefixed with the project, e.g. `SIMTOOLS_DB_PORT`, `SIMTOOLS_DB_PW`

_Originally posted by @maxnoe in https://github.com/gammasim/simtools/pull/582#discussion_r1310482483_

**Comment by GernotMaier** [comment]
What I wanted to discuss: configuration parameters can be set through command line, configuration file, or environmental variables. In the logic above, I think it would be consistent that we always expect that environmental variables related to simtools start with `SIMTOOLS_...` (e.g., `SIMTOOLS_OUTPUT_PATH`). I would apply then such changes in the code.

**Comment by orelgueta** [comment]
Agree, will you do it or do you want me to?

**Comment by GernotMaier** [comment]
Do it if you want to - just pick up the issue by assigning it to yourself.
