### ISSUE TITLE
Tests in tests/integration_tests/test_ray_tracing.py are not unit tests

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#588]
All tests in test_ray_tracing are no unit tests, but tests the several steps to run a ray tracing simulations of different telescope types.

It seems also that this is the only (?) place in the unit tests where simtel_array is called, which I dont' think we want to do in unit tests.

Summary: ray_tracing needs unit tests.

**Comment by orelgueta** [comment]
But `test_ray_tracing` is in the integration tests, not in the unit tests. I do agree that if `RayTracing` have no unit tests, then we should add them, but I wouldn't change/remove `test_ray_tracing`.

**Comment by orelgueta** [comment]
Yes please. So we also agree to keep `test_ray_tracing` as is and not remove the `simtel_path_no_mock`?

**Comment by GernotMaier** [comment]
I will open a second issue to check if tests/integration_tests/test_ray_tracing.py is necessary. 

Not spending time on it, it seems some of it duplicates application tests: `test_ssts` seems not to different from `simtools/applications/validate_optics.py`; `test_rx` can be covered using an open in derive_mirror_rnda, etc.
