### ISSUE TITLE
sim_telarray container not pushed to github packages

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#597]
The sim_telarray container is not pushed to the packages and doesn't appear in the list of packages. 

I am pretty sure that when we use `ghcr.io/gammasim/simtools-simtelarray:latest`, we are actually using the old one from the archived container repo. This causes an issue that zstd is not available in that old container, which means productions fail at the moment.

I couldn't find any difference between the settings of two containers which do get published and the sim_telarray one except two places:
```
pull_request:
    branches: ["main"]
    types: [review_requested, ready_for_review]
```
exists only for the dev/prod containers and the same is true for
```
github.event.pull_request.merged == true
```

I assume it is the latter which is responsible for the issue, since It seems the containers are built, they are just not pushed (we get the following warning at the end of the build process - `WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load`).

The easiest way to test this is by manually triggering the workflow (which I just did). If that works, I will open a short PR to add the event above to the workflow. If not, I will ask @GernotMaier to look into it.

**Comment by GernotMaier** [comment]
I agree, let's change the naming. Should we name it 'simtools-corsika-simtelarray' to reflect that it contains both simulation codes?

**Comment by orelgueta** [comment]
Yes, that sounds good.
