### ISSUE TITLE
Integration tests not using the container

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#600]
Why do the integration tests not use the sim_telarray container?

https://github.com/gammasim/simtools/blob/cf135add71d43a7816812bb2f60997b91f2b13af/.github/workflows/CI-integrationtests.yml#L80

**Comment by GernotMaier** [comment]
No good reason - simply never implemented.

**Comment by orelgueta** [comment]
OK, will see if I can do it. Not assigning myself yet since it's not high priority.
