### ISSUE TITLE
Default constructor layout = LayoutArray() not working.

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#623]
Trying to write unit tests for `LayoutArray` using a simple constructor:

```
layout = LayoutArray()
```

This gives a TypError in this [line in IOHandler](https://github.com/gammasim/simtools/blob/f9ce4ad946f3bf5451c2cf5d82dce6aac54025b4/simtools/io_handler.py#L144), as `data_path` is None.

Requires 
- review behavior of the iohandler when no paths are set.
- review and update tests for LayoutArray

**Comment by VictorBarbosaMartins** [comment]
I was wondering, should we actually allow an empty definition `layout = LayoutArray()` ? The empty definition would serve no purpose I think
