### ISSUE TITLE
Telescope classes and legend handler

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#626]
The legend_handles have trouble accepting additional telescope types and I need help in understanding how this can be improved.

Especially for PR 625, where we fail in 

```
   radius_dict = [12.5, 9.15, 7.15, 3]
    for step, tel_type in enumerate(names.all_telescope_class_names):
        assert tel_handler.radius_dict[tel_type] == pytest.approx(radius_dict[step], 1.0e-3)
        assert tel_handler.colors_dict[tel_type] == colors[step]
```
I think this even has the order of the definition of telescopes class in names.py encoded into the test?

**Comment by orelgueta** [comment]
Yes, the order, radii (as they appear in [corsika_parameters](https://github.com/gammasim/simtools/blob/main/data/parameters/corsika_parameters.yml) and colours as defined in the legend_handlers are given here explicitly in the test. Do you want me to fix this test directly in #625 to include MAGIC (or actually ignore it)?

**Comment by GernotMaier** [comment]
Could we add a generic color for non-CTA telescope, independent of the name of the telescope type? This would probably be the most consistent approach.

**Comment by orelgueta** [comment]
That is what I was planning to do, add a grey colour. I would have also added a handler for each telescope type, cause why not while we are at it.

**Comment by GernotMaier** [comment]
Good!

**Comment by GernotMaier** [comment]
@orelgueta  - maybe it is best to add the changes in legend_handlers in a branch which pulls into #625 - makes reviewing easier.

**Comment by orelgueta** [comment]
Done in #629, closing
