### ISSUE TITLE
Revisit if names of telescopes can be put into a list

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#634]
Really thing that this is not good. Could we open an issue to rethink the handling of telescope types in names.py? Best to decouple this issue from this pull request.

_Originally posted by @GernotMaier in https://github.com/gammasim/simtools/pull/629#discussion_r1354293323_

**Comment by orelgueta** [comment]
The issue refers specifically to these lines:

https://github.com/gammasim/simtools/blob/f0a3c5d6354e4862850417761d39c5cf04bbd26b/simtools/utils/names.py#L34-L37

The question is whether this can be made into a simple list instead of an explicit list. Since @VictorBarbosaMartins convinced me in the past that this is the best solution, perhaps he should weigh in =)

**Comment by VictorBarbosaMartins** [comment]
Please note that with the dictionary, the definition of names is centralized, which is good, but we will see strings of "mst", "lst" all over the place again as keys to this dictionary. For me that is still not a problem and we could go with the dictionary

**Comment by orelgueta** [comment]
But we already have a dictionary 

https://github.com/gammasim/simtools/blob/f0a3c5d6354e4862850417761d39c5cf04bbd26b/simtools/utils/names.py#L34-L45

Your described solution wasn't about the dictionary issue, but about not using strings everywhere else in the code. Once again you managed to convince me that it is the best solution to that issue, so I would vote to keep it. Unless someone has a different solution we didn't think of so far.

**Comment by GernotMaier** [comment]
I am really not convinced, but don't have a better solution at hand right now.

As mentioned, this makes modules too dependent of each other. Let's keep this issue open and deal with it later.

**Comment by GernotMaier** [comment]
I am not convinced, but I accept this...let's close this issue for now. In future, I expect that we will have a lot of the information which is currently in names.py in the database.
