### ISSUE TITLE
Allow simulator.py to get as input the corsika_parameters.yml file

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#640]
The current implementations of [simulator.py](https://github.com/gammasim/simtools/blob/main/simtools/simulator.py) uses the corsika parameter file hard coded from [corsika_parameters.yml]([corsika_parameters.yml](https://github.com/gammasim/simtools/blob/main/data/parameters/corsika_parameters.yml)). However, to be able to pass a configuration with a different atmospheric absorption file, we need to include the number of the atmosphere or the atmospheric absorption file in the "IACT_TUNING_PARAMETERS" key inside `corsika_parameters.yml`.

Therefore, I propose allowing the user to pass a different file with a different corsika parameter configuration through the `self._corsika_parameters_file` attribute of the Simulator() class in simulator.py. With that we will be able to simulate with different atmospheres.

Do you agree with the solution @GernotMaier , @orelgueta ?

**Comment by orelgueta** [comment]
If I am not mistaken, you can simply provide a different file name by adding a key in the configuration dictionary. In the old production script it would be in `shower_configs["corsika_parameters_file"] = new_file`. I think you can also just add that key into the production configuration yaml file under `showers`.
