### ISSUE TITLE
sphynx link not working 

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#653]
When attempting to open simpipe documentation from the link displayed in the main page, we get the following error:

404
File not found

We believe that the link is broken.

**Comment by GernotMaier** [comment]
(this is a bit of detective work)

As a quick follow up: the deployment / artifact upload is not working: https://pipelinesghubeus24.actions.githubusercontent.com/DnqbUKcux9cWS0yRiAj6t2dYvyqC1dz2kswSMAwliWqUVCBWsD/_apis/pipelines/1/runs/2105/artifacts?artifactName=github-pages&%24expand=SignedContent

Last successful deployment was Oct 16, 1:01 pm, so we need to check what happened in PRs #622, #625, #636.

Web search shows that this is related to introduced some weird non-standard characters into the code. Need to check for this.
