### ISSUE TITLE
Wrong naming of coordinate systems in `print_array_elements`

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#658]
The naming of the coordinate system `CORSIKA` is not correct in `print_array_elements` and classes associated with it.

- CORSIKA coordinate systems are aligned with geomagnetic North
- this coordinate system in simtools is aligned with geographic North (the difference is handled in CORISKA using the `ARRANG` parameter)

Find a better naming "ground or simtools coordinates?" and replace it accordingly in the code.

**Comment by orelgueta** [comment]
I would vote for `ground` or `local` coordinates. `sim_telarray` coordinates (not `simtools`) would also be reasonable, but is a bit too specific I think.
