### ISSUE TITLE
Implement the option to save simtel_array histograms to hdf5 tables and export them

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#663]
I would like to adapt `SimtelHistograms` from `simtel_histograms.py` to allow saving the histograms to hdf5 files, as it is already done in `CorsikaHistograms` from `corsika_histograms.py`. This will standardise histograms produced by corsika and simtel_array within simtools. The advantage is to be able to use the same tool later to compare the histograms among different simulations.

**Comment by kosack** [comment]
By the way, this functionality is already _partially_ in ctapipe and it's HDF5 DLx data format. I say partially, as we only currently write out the simulated events histograms (the ones we need to compute sensitivity later).  But it could easily be extended.

**Comment by VictorBarbosaMartins** [comment]
Hi @kosack, thanks for this suggestion. For now I am keeping it simple in simtools, using `write_table` from `ctapipe.io.astropy_helpers` to append all the histogram tables to the hdf5 file. I will further look into this to see if we can focus on the simulated events histograms instead of all histograms, in which case I could change to use the ctapipe data model as you mentioned.
