### ISSUE TITLE
Review contents of general.py

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#665]
[simtools/utils/general.py](simtools/utils/general.py) starts to become a collection of "unrelated" functions which will be difficult to maintain in future.

Suggest to review the contents and if necessary restructure.

**Comment by VictorBarbosaMartins** [comment]
agree. should we add this to the maintenance period?

**Comment by VictorBarbosaMartins** [comment]
Oh, I see it is already there

**Comment by GernotMaier** [comment]
These are my suggestions:

- add docstring at the top explaining that this should be used for very generic functions only; it is used in many places and no slow imports should be introduced
- `file_has_text` is not used anywhere in simtools (except in its own unit tests). Suggest to move it into `tests/conf.py`, where we have functions used by tests only
- move `rotate` and and `convert_2D_to_radial_distr` into a new module (transformations.py?)
- `save_dict_to_file` saves a dict to yaml. This is used only once in the code (in corsika_histograms). We should decide if we use generic functions or the simple yaml.dump syntax.

(see PR #704)

**Comment by VictorBarbosaMartins** [comment]
Agree with the first two bullet points. In regard to the third one, I would call such a module `geometrical_transformations` or `geometry`. I don't have a strong opinion on the `save_dict_to_file`. When I coded this, I was expecting that this could be useful elsewhere, but a single `yaml.dump` does the job as well. I suggest to always use the yaml module from `astropy.io.misc.yaml` (not sure we are consistently using the same yaml module)

**Comment by GernotMaier** [comment]
Not sure about `geometry`, these are transformations, or?

**Comment by VictorBarbosaMartins** [comment]
Just to avoid more than one person working on the same thing, I am starting working on this now.
