### ISSUE TITLE
Sites branch - what to do?

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#667]
This is work from early 2020 and we should decide if this is work in progress, outdated, or ready to be merged.

https://github.com/gammasim/simtools/compare/sites

**Comment by VictorBarbosaMartins** [comment]
I think the most important features from this branch were already taken into account in #429 and #441. From my side we can delete it, but let's wait for @orelgueta's response

**Comment by VictorBarbosaMartins** [comment]
The only function that is not implemented yet is the option to plot a sub-array:
```
def selectSubArray(fileName, hyperArray):

    subArray = np.loadtxt(fileName, dtype=('U10'), usecols=(4))
    telescopes = hyperArray[[telNow in subArray for telNow in hyperArray['telescope_name']]]

    return telescopes
```
As this is a very simple function and we do not need it now, I suggest to close this. However, if we want to allow working with sub arrays as pointed out in #115, we could implement it in the plotting tool as well.
