### ISSUE TITLE
Non-active branches 

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#668]
Not sure what the status of the following branches are:

- https://github.com/gammasim/simtools/tree/update-README
- https://github.com/gammasim/simtools/tree/github_io_updates

@tobiaskleiner - both of them belong to a closed pull request. Is this still work in progress or should we delete them?

**Comment by tobiaskleiner** [comment]
@GernotMaier they can be deleted. It was a duplication of another PR.

**Comment by tobiaskleiner** [comment]
Deleted them now. Closing.
