### ISSUE TITLE
Integration tests create a local directory `directory_for_grid_upload`

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#680]
Test should not leave locally any data, this directory should probably be created in tmp dir.

**Comment by GernotMaier** [comment]
So why can't the integration tests not write to `tmp_test_directory`?

**Comment by orelgueta** [comment]
It can, that's the second option I suggested because the application explicitly writes to the local directory and ignores the `output_directory`.

**Comment by GernotMaier** [comment]
Can you explain why it ignores `output_directory`?

If this is absolutely necessary, why not setting `output_directory` to the local directory as default? This would still allow to change it if necessary.

**Comment by orelgueta** [comment]
Yes, setting `output_directory` to the local one by default might work. I need to test this, will look into it when we start maintnance.
