### ISSUE TITLE
Applications are painfully slow to even start.

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#681]
This is really starting to get an issue, as it slows down developing, testing, everything.

Running e.g.,
```
 python simtools/applications/validate_file_using_schema.py --help
```

Take >3 sec for me. This should just print help.

Running

```
python -X importtime simtools/applications/validate_file_using_schema.py --help
```
shows that it us due to extensive importing (see attachment).

In this example, it is e.g., not clear why ctapipe is imported.

[import.txt](https://github.com/gammasim/simtools/files/13376329/import.txt)

**Comment by GernotMaier** [comment]
To do further, this looks like that this is almost exclusively due to ctapipe.

I suggest to remove anything related to ctapipe from simtools.utils.general and move it into a separate module. The `general` module is used a lot, but not very often for the hdf5 functionality.

@VictorBarbosaMartins - is it fine for you if I move this out of general.py?

**Comment by GernotMaier** [comment]
PR #682 addresses most of this issue.

When we discuss the cleanup of general.py, we should address the remaining issues (e.g., moving the coordinate transformations somewhere else will remove the dependency on astropy.coordinates.errors (1/3 of import time). Rest is due to astropy.units, which is something we need.

**Comment by VictorBarbosaMartins** [comment]
> This looks like that this is almost exclusively due to ctapipe.
> 
> I suggest to remove anything related to ctapipe from simtools.utils.general and move it into a separate module. The `general` module is used a lot, but not very often for the hdf5 functionality.
> 
> @VictorBarbosaMartins - is it fine for you if I move this out of general.py?

Hi Gernot. That is probably a good idea, Im fine with it
