### ISSUE TITLE
Array plotting suggestions

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#69]
Some minor suggestions for the array plotting - all not high priority:

I use in the following:
Telescope name: e.g., LST-01, MST-03, ...
Telescope id: sim_telarray ID, 1, 2, 3,...

**Plots:**
- [ ] axes: East (m) for x-axis, and North (m) for y-axis (correct? I see that you rotate by 270 deg?)
- [ ] allow to use other coordinate systems for plotting (e.g, UTM)
- [x] don't add LST to legend, if there are no LSTs (same for any other telescope type
- [x] find it useful to have a text line somewhere '4 LSTs, 25 MSTs, 70 SSTs' (easy to find problems in arrays, if a telescope is missing)
- [ ] option to plot sim_telarray telescope ID instead of telescope name
- [x] option for output file format (png or pdf)
- [ ] simple way to plot all layouts from a list in a file 
- [ ] automatic scaling of x/y to size of the array (I think you do, but does that work when the layout is not symmetric and for large negative x or y?) Suggest that x and y are always of the same scale 
- [x] figure should be a square (equal scale on both axis)
- [x] smaller font for title (or remove telescope layout?)
- [ ] option to add a background image (e.g, see attachment; horrible way to make it fit)
- [ ] plot distribution of telescope distances (per telescope type)

Not really plotting, but it would be nice to also (should maybe go into a different issue):

**Converters of telescope IDs:**
- [ ] produce new array list which replaces MSTX with MSTY (e.g., produce a list with MSTFs at the same position as a given list with MSTNs)
- [ ] convert a prod3b list to prod5 (by checking telescope positions and telescope types) or using a map of telescope IDs vs telescope names

**Other points:**
- [ ] print list of N neighbouring to a given telescope (simply a list sorted in telescope distance)
- [ ] compare telescope list A and B and print differences (to easily see if A is a subarray of B)

**Comment by orelgueta** [comment]
All great suggestions, will work on then slowly. I will also answer the few questions soon, but I am just curious about

> option to add a background image (e.g, see attachment; horrible way to make it fit)

The attachment is missing, may I ask you to please upload it? I wonder how it looks and what did you actually do to get it.

**Comment by GernotMaier** [comment]
![Prod5-N D2-4LSTs09MSTs-MSTF](https://user-images.githubusercontent.com/14001688/93378403-b4aae600-f85c-11ea-933a-319e84165c42.png)

**Comment by orelgueta** [comment]
Ahh OK, this I have seen. You made that with ROOT I assume? Don't think it looks too bad, but it's not entirely accurate I guess. Maybe we can do something better.

**Comment by GernotMaier** [comment]
Question is how accurate we need it. It is for illustration only - of course you can get it better if you spend a lot of hours on it...

**Comment by orelgueta** [comment]
Implemented a few of these points, please see some comments below.

> I use in the following:
> Telescope name: e.g., LST-01, MST-03, ...
> Telescope id: sim_telarray ID, 1, 2, 3,...

Names is a longer discussion I guess, will be changed once a solution is reached.
 
> * [ ]  axes: East (m) for x-axis, and North (m) for y-axis (correct? I see that you rotate by 270 deg?)

Been meaning to ask, I have to rotate by 270 deg to get this orientation, why do we save the positions in a different orientation? Currently the rotation angle is hard coded in the application (not too bad), should it be given as an option to the user or will we always rotate by 270?
Either way, the axes labels were set as you suggest.

> * [ ]  allow to use other coordinate systems for plotting (e.g, UTM)

This will wait until after your module is integrated into gammasim-tools.

> * [ ]  don't add LST to legend, if there are no LSTs (same for any other telescope type

Done.

> * [ ]  find it useful to have a text line somewhere '4 LSTs, 25 MSTs, 70 SSTs' (easy to find problems in arrays, if a telescope is missing)

Added to the legend. If you prefer a line, please let me know.

> * [ ]  option to plot sim_telarray telescope ID instead of telescope name

Those are not saved in the ECSV file, do you mean to match them to a separate list by position?

> * [ ]  option for output file format (png or pdf)

Done.

> * [ ]  simple way to plot all layouts from a list in a file

Still pending.

> * [ ]  automatic scaling of x/y to size of the array (I think you do, but does that work when the layout is not symmetric and for large negative x or y?) Suggest that x and y are always of the same scale
> * [ ]  figure should be a square (equal scale on both axis)

These two points come together. The x/y should scale automatically and the plot should now be square. However, I am not sure if this answers your request. If not, could you please send me a couple of "bad" examples so I can know what you mean?

> * [ ]  smaller font for title (or remove telescope layout?)

Reduced font, but it might still be too long. Isn't the telescope layout useful there?

> * [ ]  option to add a background image (e.g, see attachment; horrible way to make it fit)

Still pending.

> * [ ]  plot distribution of telescope distances (per telescope type)

Still pending.

> * [ ]  compare telescope list A and B and print differences (to easily see if A is a subarray of B)

Would be nice to also plot them as comparison. Will do that as well.

**Comment by kosack** [comment]
I'd suggest you implement any array plotting in ctapipe.visualization.ArrayDisplay and use that here as a dependency.  Currently it's quite simplistic, and only plots the integer tel_ids, but it would be easy to extend.  I'd rather have all plotting in one place, rather than 2 plotting systems (which will almost certainly lead to confusion if they use different options using different conventions!)

**Comment by orelgueta** [comment]
We were discussing where these things should go and figured that the sub-array plotting functionality will be useful only for simulation in the long run. That's why we decided to keep it here. 
However, we could probably keep the sub-array selection here and implement and use the plotting from `ctapipe.visualization.ArrayDisplay`.

**Comment by GernotMaier** [comment]
Still need to try it out, here a few replies.

> Implemented a few of these points, please see some comments below.
> 
> 
> 
> > I use in the following:
> 
> > Telescope name: e.g., LST-01, MST-03, ...
> 
> > Telescope id: sim_telarray ID, 1, 2, 3,...
> 
> 
> 
> Names is a longer discussion I guess, will be changed once a solution is reached.
> 
>  
> 
> > * [ ]  axes: East (m) for x-axis, and North (m) for y-axis (correct? I see that you rotate by 270 deg?)
> 
> 
> 
> Been meaning to ask, I have to rotate by 270 deg to get this orientation, why do we save the positions in a different orientation? Currently the rotation angle is hard coded in the application (not too bad), should it be given as an option to the user or will we always rotate by 270?
> 
> Either way, the axes labels were set as you suggest.

Not sure what the question is:

- we have a mismatch in the axis orientation?
- why do I rotate by 270 deg? (Because this is the Eventdisplay system...)

> 
> 
> 
> > * [ ]  allow to use other coordinate systems for plotting (e.g, UTM)
> 
> 
> 
> This will wait until after your module is integrated into gammasim-tools.
> 
> 
> 
> > * [ ]  don't add LST to legend, if there are no LSTs (same for any other telescope type
> 
> 
> 
> Done.
> 
> 
> 
> > * [ ]  find it useful to have a text line somewhere '4 LSTs, 25 MSTs, 70 SSTs' (easy to find problems in arrays, if a telescope is missing)
> 
> 
> 
> Added to the legend. If you prefer a line, please let me know.
> 
> 
> 
> > * [ ]  option to plot sim_telarray telescope ID instead of telescope name
> 
> 
> 
> Those are not saved in the ECSV file, do you mean to match them to a separate list by position?

Missed this. I still have to come up with a format, but I would say that the sim-telarray telescope ID is an optional column in the ecsv file.


> 
> 
> 
> > * [ ]  option for output file format (png or pdf)
> 
> 
> 
> Done.
> 
> 
> 
> > * [ ]  simple way to plot all layouts from a list in a file
> 
> 
> 
> Still pending.
> 
> 
> 
> > * [ ]  automatic scaling of x/y to size of the array (I think you do, but does that work when the layout is not symmetric and for large negative x or y?) Suggest that x and y are always of the same scale
> 
> > * [ ]  figure should be a square (equal scale on both axis)
> 
> 
> 
> These two points come together. The x/y should scale automatically and the plot should now be square. However, I am not sure if this answers your request. If not, could you please send me a couple of "bad" examples so I can know what you mean?
> 
> 
> 
> > * [ ]  smaller font for title (or remove telescope layout?)
> 
> 
> 
> Reduced font, but it might still be too long. Isn't the telescope layout useful there?

I mean the word 'telescope layout'. Please keep the name of the layout (but we know that it is a layout, so don't write it on the plot).


> 
> 
> 
> > * [ ]  option to add a background image (e.g, see attachment; horrible way to make it fit)
> 
> 
> 
> Still pending.
> 
> 
> 
> > * [ ]  plot distribution of telescope distances (per telescope type)
> 
> 
> 
> Still pending.
> 
> 
> 
> > * [ ]  compare telescope list A and B and print differences (to easily see if A is a subarray of B)
> 
> 
> 
> Would be nice to also plot them as comparison. Will do that as well.
> 
> 
> 
>

**Comment by orelgueta** [comment]
> > Been meaning to ask, I have to rotate by 270 deg to get this orientation, why do we save the positions in a different orientation? Currently the rotation angle is hard coded in the application (not too bad), should it be given as an option to the user or will we always rotate by 270?
> > Either way, the axes labels were set as you suggest.
> 
> Not sure what the question is:
> 
> * we have a mismatch in the axis orientation?
> * why do I rotate by 270 deg? (Because this is the Eventdisplay system...)

No mismatch, was just wondering about the orientation in the file. Now I see that it follows the sim_telarray convention and we want the plot to be north-aligned (and ED aligned). So I guess it will stay 270 deg for the foreseeable future and I can keep the hardcoded value.


> > Added to the legend. If you prefer a line, please let me know.
> > > * [ ]   option to plot sim_telarray telescope ID instead of telescope name
> > 
> > 
> > Those are not saved in the ECSV file, do you mean to match them to a separate list by position?
> 
> Missed this. I still have to come up with a format, but I would say that the sim-telarray telescope ID is an optional column in the ecsv file.

OK, when we have an example file I can implement it, no problem. I might try producing this example file myself if I get a chance.


> > Reduced font, but it might still be too long. Isn't the telescope layout useful there?
> 
> I mean the word 'telescope layout'. Please keep the name of the layout (but we know that it is a layout, so don't write it on the plot).

Done.

**Comment by GernotMaier** [comment]
Many of the discussion points from above come from an era of telescope optimization and are not needed anymore. I will close this issues therefore.

Some of the issues are also addressed in #947 (like plotting from a list, etc).
