### ISSUE TITLE
Slow starting of unit tests

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#694]
pytest is very slow to start, even for very simple tests (>5 seconds on my laptop). Very hard to debug with this slow response.

After investigation, it is the same issue as realized recently with general.py (#681): any including of ctapipe means that tools slow down due to a large number of slow imports.

I suggest to consider removing the following two fixtures from conftest.py:
```
@pytest.fixture
def corsika_histograms_instance(io_handler, corsika_output_file_name):
    return CorsikaHistograms(
        corsika_output_file_name, output_path=io_handler.get_output_directory(dir_type="test")
    )


@pytest.fixture
def corsika_histograms_instance_set_histograms(db, io_handler, corsika_histograms_instance):
    corsika_histograms_instance.set_histograms()
    return corsika_histograms_instance

```

Victor, is this possible without a huge amount of work? 

I will also investigate with ctapipe developers if this is a feature or an issue.

**Comment by GernotMaier** [comment]
See also https://github.com/cta-observatory/ctapipe/issues/2476

**Comment by VictorBarbosaMartins** [comment]
Hi @GernotMaier. Yes, this should be simple, as the fixtures are likely used in only two different places. I see two options:
- Either we repeat the definition of the fixture
- Or we import one test*.py inside the other, which I don't see as a problem, as both are related to corsika histograms.

Should I go for option 2?

**Comment by GernotMaier** [comment]
I leave it to you what is best - less dublication is definitively good.
