### ISSUE TITLE
Bug in reading u.Quantities from config dict in configurator?

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#706]
`simtools/configuration/configurator.py` introduces a lot of flexibility by allowing to consistently config simtools using the command line, configuration file, or simply a dictionary. All is handled by argparse.

I do think that inserting an u.Quantity through a dictionary is not handled correctly, see the following line:

https://github.com/gammasim/simtools/blob/97c22a5898cf3d767672de282e7045f914ec90f3/simtools/configuration/configurator.py#L355

What happens: a configuration parameter `{"a": 5.*u.m}` is converted to a argparse parameter `--a "5."`. But where does the unit go?

I think it should be  `--a "5. m"`, meaning the line

`_list_args.append(str(value.value))`

should be replaced by

`_list_args.append(str(value))`.

Does this make sense?

**Comment by VictorBarbosaMartins** [comment]
I agree we have to deal better with the units in this case, but I think that passing units in the command line is not the best. Passing units in the command line would mean that every parameter is a string, which makes it more difficult to check whether the unit passed (and the format) makes sense. Alternatively, in case the parameters are passed via a dictionary/file, I would require the presence of and would read the unit. On the other hand, if the parameters are passed via command line, I would require  the parameter (float) passed in a specific unit (suggestion). Does that make sense?

**Comment by GernotMaier** [comment]
I think we are doing a very good job with units!

A string can be converted to a quantity by e.g.,  `u.Quantity("50. deg")` - so this really shouldn't be a problem.

Note that above errors accepts units from the command line by ignoring them, which is simply wrong.
