### ISSUE TITLE
parameter metadata not used in the function

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#710]
https://github.com/gammasim/simtools/blob/4817fc03c10b00814875476218bd6eac4cd056e6/simtools/data_model/model_data_writer.py#L87

The parameter `metadata` is not used in the function and should be likely removed

**Comment by GernotMaier** [comment]
Yes, this is on the.

pylint is catching this issues, so I connect this to the linter branch.
