### ISSUE TITLE
h5py warning in unit tests

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#722]
Not sure if this is a simtools, ctapipe, or hd5 issue. 

Unit tests generate the following warning:

```
tests/unit_tests/data_model/test_model_data_writer.py::test_write_data
  /Users/maierg/miniconda3/envs/simtools-dev/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.2, this may cause problems
    _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
```

(at least on my setup).

**Comment by VictorBarbosaMartins** [comment]
Hi @GernotMaier. I don't see the warning when running the pytest from within the container (current main). However, I activated the user logger (```pytest tests/unit_tests/data_model/test_model_data_writer.py::test_write_data -o log_cli=true```) to see if I would find the warning and it turned out there are some weird issues with the io_handler

```
------------------------------------------------------ live log call -------------------------------------------------------
DEBUG    simtools.io_operations.io_handler:io_handler.py:33 Init IOHandler
ERROR    simtools.io_operations.io_handler:io_handler.py:98 Error creating output directory name from simtools-result
INFO     simtools.data_model.model_data_writer:model_data_writer.py:124 Writing data to None
ERROR    simtools.data_model.model_data_writer:model_data_writer.py:129 Error writing model data to None.
INFO     simtools.data_model.model_data_writer:model_data_writer.py:124 Writing data to /tmp/pytest-of-root/pytest-4/test-data0/test_file.ecsv
PASSED                                                                                                               [100%]
```

**Comment by GernotMaier** [comment]
Seems to be visible only in the conda environment.

The io_handler log messages are expected: these are tests and not all values are  always properly defined in tests.

**Comment by VictorBarbosaMartins** [comment]
> Seems to be visible only in the conda environment.
> 
> The io_handler log messages are expected: these are tests and not all values are always properly defined in tests.

Then we could close the issue, no? The conda env is not part of simtools.

**Comment by GernotMaier** [comment]
I am mostly using simtools in a conda environment, also most of the tests are using mamba/conda and the warning is also visible in the unit tests on github actions.

Probably requires a short web search to understand what is going on.

**Comment by GernotMaier** [comment]
Closing this issue: I have cross checked the output of the unit tests for the different python versions and these warnings disappeared. As discussed above, these are hd5 issues and probably this package has been updated in the meanwhile.
