### ISSUE TITLE
Introduce consistent naming of DL3 data model and model parameter schema files

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#738]
This issue is fairly broad, but it is here to replace a TODO in the code (as per #715)

https://github.com/gammasim/simtools/blob/7278a5229f5fd5940fbff1f4473f71f812ef3ac3/simtools/data_model/metadata_collector.py#L282

**Comment by GernotMaier** [comment]
I've looked at this again and think it is not relevant issue. We are not sure much bothered about DL3, but more about the data model developed to describe the instrument (Mathieu et al). This is still ongoing and when finished will required a couple of changes.

Especially instrument:classes will changes (but are also nowhere really used in simtools).

I therefor suggest to close this issue.

**Comment by GernotMaier** [comment]
Closing this (as there are no objections)
