### ISSUE TITLE
improve testing of old production tool after merging #726

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#741]
I don't mind that it is a bit uglier now, as it seems to be working. With this, the old production tool is again functional and has a zero padding (did not think this would be so important.). I tested locally (merging #740 before) as I suggested before and, therefore, I am approving.

As a side note, the tests are still not sufficient to detect whenever the tool gets broken again. So, I will wait for us to merge #726 before implementing better tests.

_Originally posted by @VictorBarbosaMartins in https://github.com/gammasim/simtools/issues/735#issuecomment-1852322878_

**Comment by VictorBarbosaMartins** [comment]
I am starting to implement this but I wanted to consult first if you agree with the approach.

In fact, running the production with `--array-only` option depends on the results from simualting with `--showers-only`. When simulation with  `--array-only`, I can still point `simtel_path` to the output of the production simulated with `--showers-only`, I can only guarantee that the one is ran after the other if I alphabetically set that up in the conf test name, e.g. `production_1_showers_only` and `production_2_array_only`. Is that a good solution, or do you have a better one?

**Comment by orelgueta** [comment]
I actually noticed this issue that `--array-only` depends on `--shower-only` now while working on #746. What's weird is that the application does not raise an error even when it doesn't find the input file. That should definitely be fixed.

In terms of the solution you propose, I suggest a different one. Produce one small corsika file (perhaps by running `--showers-only` and put that file in `tests/resources`. This will break the interdependency and in general would be more consistent with how we do things.

**Comment by VictorBarbosaMartins** [comment]
exactly. that was the reason I wanted to improve this test. The tool was broken and we didnt realize for a while.

Ok, great. that a better solution indeed!

**Comment by orelgueta** [comment]
Before you make too many changes, maybe wait for #746 or merge it to your branch because I changed some of the parameters to make the test run quicker.

**Comment by VictorBarbosaMartins** [comment]
Hmm, it turned out that your idea is not that simple to implement. We would have to include the entire subdirectories, i.e., `corsika-data/North/gamma/data/` which is not ideal. Also, `--data_directory` defines both the corsika and simtel_array data directories, which means that by defining it for corsika, the production tool would save simtel_data inside it, hence saving test files to the wrong places. I will have to rethink this but at the moment running in sequence sounds like a more ideal solution

**Comment by orelgueta** [comment]
Wait, why do you need to define the full structure and cannot provide a file directly as input? 
If that's not an option of the `production.py` application, then it should be added because when we save files on the grid we remove the structure obviously. 

I don't really follow the issue with the --data_directory. Maybe you show/explain it to me tomorrow.

**Comment by VictorBarbosaMartins** [comment]
Will `production.py` be used in the grid? If only the new production tool will be used in the future, it is not worth implementing new features in the old production tool now. It would only be nice to fix it (as you did) and now test it correctly. I still vote for the tests running in sequence, it is to me the simplest solution.
