### ISSUE TITLE
Integration test - time of executation

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#743]
Integration tests, take a little while and we should see if there is an easy way to accelerate without loosing testing power.

This is the ranking (from my laptop):

```
52.29s call    simtools-derive-mirror-rnda_psf_mean
235.96s call    simtools-derive-mirror-rnda_psf_random_flen
234.93s call    simtools-derive-mirror-rnda_psf_measurement0
226.37s call    simtools-derive-mirror-rnda_psf_measurement1
202.37s call    simtools-tune-psf_run
65.94s call     simtools-production_array_only
48.58s call     simtools-generate-simtel-array-histograms_hist_file_names0
42.32s call     simtools-generate-corsika-histograms_individual_telescopes_and_indices
40.19s call     simtools-simulate-prod_gamma_20_deg_pack_for_grid
38.66s call     simtools-generate-simtel-array-histograms_hist_file_names_pdf_hdf5
```

Possibly some easy changes can reduce this significantly:

- simtools-derive-mirror-rnda - testing 3 instead of 10 mirrors might be enough (see [this line](https://github.com/gammasim/simtools/blob/d984fa0bf0ee73ab8327c7437a0da5b12d07a7f0/simtools/applications/derive_mirror_rnda.py#L360); tried to change this, but tests then run forever)
- simtools-tune-psf_run - runs 10000 photons, maybe for testing 1000-2500 are enough?

**Comment by orelgueta** [comment]
I assign to myself cause I am taking care of all tests other than the ones @VictorBarbosaMartins is dealing with (in #744) and I assume in a different PR also the `simtools-generate-corsika-histograms_individual_telescopes_and_indices` test.

**Comment by GernotMaier** [comment]
Yes, thanks!

Note that if you add any flags (like --test), just add a line with `TEST: true` into the configuration file for the corresponding application test.

**Comment by VictorBarbosaMartins** [comment]
> I assign to myself cause I am taking care of all tests other than the ones @VictorBarbosaMartins is dealing with (in #744) and I assume in a different PR also the `simtools-generate-corsika-histograms_individual_telescopes_and_indices` test.

Sure. I think there will be no conflicts, we can both work on improving different applications.

**Comment by orelgueta** [comment]
Yes. I need to make changes to the configuration of tests, but i will do it once here (useless) and once in the branch with the new applications (it's just a tiny change).

**Comment by orelgueta** [comment]
Latest ranking:

```
============================================================================= slowest 10 durations ==============================================================================
31.98s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-derive-mirror-rnda_psf_mean]
31.26s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-derive-mirror-rnda_psf_random_flen]
30.61s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-derive-mirror-rnda_psf_measurement0]
30.09s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-derive-mirror-rnda_psf_measurement1]
11.96s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-simulate-prod_gamma_20_deg]
11.86s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-simulate-prod_gamma_20_deg_pack_for_grid]
11.79s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-tune-psf_run]
10.43s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-production_array_only]
6.81s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-produce-array-config_run]
5.91s call     tests/integration_tests/test_applications_from_config.py::test_applications_from_config[simtools-validate-camera-efficiency_MST-FlashCam-D]
========================================================================= 69 passed in 62.86s (0:01:02) =========================================================================
```

Will open a PR since I think it's already good enough.
