### ISSUE TITLE
Reading of 'corsika' parameters like sphere center, radius, site altitude

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#753]
I am trying to understand where all information is coming from for the coordinate transformations and I am little bit confused by these lines (which I think I have written):

https://github.com/gammasim/simtools/blob/c1b42a652bab8638e3e69e7e0d16a17b961b30d7/simtools/layout/array_layout.py#L178

Depending on how the ArrayLayout class is called, the file [data/parameters/corsika_parameters.yml](data/parameters/corsika_parameters.yml) is read and the site altitude (and other parameters) is used from there. 

This is not what we want, or does anyone knows a good reason to do this?

Model parameters should be read from the database (and we could discuss if we can read it for historical reasons as well from the header of the ecsv file; but not from a hardwired file, or?)

**Comment by orelgueta** [comment]
That's because the telescope sphere radius and centre are not in the DB. Many of the CORSIKA parameters are not in the DB because we are not clear yet on which ones we need to list and the versioning of them. We planned to finalise it after the CORSIKA histograms project, but because it was somewhat abandoned, we also "forgot" to go back and put CORSIKA stuff in the DB.

**Comment by VictorBarbosaMartins** [comment]
I am fine with getting the telescope and site parameters from the DB but the remaining parameters are configuration parameters. Configuration parameters are not fixed for every simulation and having them in a file facilitates changing them.

**Comment by VictorBarbosaMartins** [comment]
I see also that the atmospheric file is inside the site parameters in the file and that we would like to able to change as well. `corsika_sphere_center` and `corsika_sphere_radius` are supposed to be always fixed and could go into the DB.

**Comment by GernotMaier** [comment]
OK - I will try and remove the telescope specific values from this file and see how to get it into the DB. 

(seems like I am going deep into rabbit hole right now - there are a couple of surprising dependencies)

**Comment by GernotMaier** [comment]
And note also that 'corsika_sphere_center' is the height of the elevation axis above ground. Depending on the ground definition, this actually might be slightly different for each telescope.

**Comment by orelgueta** [comment]
Specifically the sphere centre and radius can be added to the telescope collection in the DB. All other CORSIKA parameters require some thinking since they are not telescope/site dependent. We might need a separate collection for that.

**Comment by GernotMaier** [comment]
These values should go into the DB:

- corsika_sphere_radius
- corsika_sphere_center
- OBSLEV
- MAGNET
- ARRANG

In `data/parameters/corsika_parameters.yml`, ARRANG is commented out. This wouldn't be correct, as we define telescope position using geographic north (and not magnetic north).

All other parameters are obviously configuration parameters.

**Comment by orelgueta** [comment]
But do you agree/think that the corsika sphere parameters should go into the telescope parameters?

OBSLEV is saved as "altitude" in the sites collection of the DB. MAGNET is saved as "magnetic_field". 

ARRANG indeed should be put into the DB. We need to think a bit how to save it because it is for specific years (in particular, 2020 and 2025). Then we extrapolate/interpolate for other years in the code.

**Comment by GernotMaier** [comment]
> But do you agree/think that the corsika sphere parameters should go into the telescope parameters?

Yes, and we have already schema files:

- https://github.com/gammasim/workflows/blob/main/schemas/telescope_axes_height.schema.yml (which is the former sphere center; not sure if we are the stage of improve parameter naming already...)
- https://github.com/gammasim/workflows/blob/main/schemas/telescope_sphere_radius.schema.yml


> 
> OBSLEV is saved as "altitude" in the sites collection of the DB.

OK!

> MAGNET is saved as "magnetic_field".
> 
> ARRANG indeed should be put into the DB. We need to think a bit how to save it because it is for specific years (in particular, 2020 and 2025). Then we extrapolate/interpolate for other years in the code.

This is true - also for magnetic field. The question is if we want to interpolate it, or if we use the geomag program to calculate for a given date the field parameters each time we generate a configuration. This way we would rely on the experts (I am not sure if a linear interpolation is correct - although it does not change dramatically and we are probably fine)

**Comment by orelgueta** [comment]
> > But do you agree/think that the corsika sphere parameters should go into the telescope parameters?
> 
> Yes, and we have already schema files:
> 
> * https://github.com/gammasim/workflows/blob/main/schemas/telescope_axes_height.schema.yml (which is the former sphere center; not sure if we are the stage of improve parameter naming already...)
> * https://github.com/gammasim/workflows/blob/main/schemas/telescope_sphere_radius.schema.yml

Should these be the first parameters we verify, validate and push to the DB then? I don't mind the change of name. It should be fairly simple to adapt to. 

> > ARRANG indeed should be put into the DB. We need to think a bit how to save it because it is for specific years (in particular, 2020 and 2025). Then we extrapolate/interpolate for other years in the code.
> 
> This is true - also for magnetic field. The question is if we want to interpolate it, or if we use the geomag program to calculate for a given date the field parameters each time we generate a configuration. This way we would rely on the experts (I am not sure if a linear interpolation is correct - although it does not change dramatically and we are probably fine)

I suggest we start from the simple case of storing 2020 and 2025 and the simple interpolation/extrapolation. In the future we can implement an external tool. 
Once again, we could include these parameters using the new schema or I upload these parameters as they are now.

**Comment by GernotMaier** [comment]
Don't do anything. These parameters (at least those required for the coordinate transformations) are my first test cases for the new parameter structure.

**Comment by GernotMaier** [comment]
As a follow up to this: do we all agree that the parameters above (all CORSIKA parameter related to the simulation model; not those related to the configuration) should go into the database **and** we remove them from [data/parameters/corsika_parameters.yml](data/parameters/corsika_parameters.yml) and the headers of the array layout tables (ecsv headers)?

I do think this is the correct why and this would simplify the approach significantly! (otherwise we have to check for the corsika model parameters in the DB, in the yaml file, and in the ecsv headers...a lot of if statements...)

**Comment by VictorBarbosaMartins** [comment]
> As a follow up to this: do we all agree that the parameters above (all CORSIKA parameter related to the simulation model; not those related to the configuration) should go into the database **and** we remove them from [data/parameters/corsika_parameters.yml](data/parameters/corsika_parameters.yml) and the headers of the array layout tables (ecsv headers)?
> 
> I do think this is the correct why and this would simplify the approach significantly! (otherwise we have to check for the corsika model parameters in the DB, in the yaml file, and in the ecsv headers...a lot of if statements...)

Having them in one place is sufficient, and nothing better than having them in the DB.

**Comment by orelgueta** [comment]
I agree as well

**Comment by GernotMaier** [comment]
Implemented with #761
