### ISSUE TITLE
set_mongo_db_config not called anywhere - still needed?

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#759]
see https://github.com/gammasim/simtools/blob/35a0d40338828c7d6879b64b64b1c6fb67043766/simtools/db_handler.py#L72

(not really important - just noticed that this is not used)

**Comment by orelgueta** [comment]
It should probably be changed to be a setter for a property instead. Then, we will need to add also a public method to set up the connection. These changes would allow to define the DB handler without actually setting up the connection, in case it is necessary. 

It makes sense to have this option for an API. However, I would also agree that it is not needed at the moment, and there's no reason to support/implement functionality that is not used. So, I leave it up to you to decide which of the options we should go for (I can do the implementation if you decide to keep it).

**Comment by GernotMaier** [comment]
Would we need this in the near future? If yes, then let's keep it, it is only a couple of lines (which at the same time speaks for removing it, as it can be easily added again). So let's remove it, unless you see that we need it soon.
