### ISSUE TITLE
github complains about missing tests in PR-unrelated file

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#764]
<img width="1459" alt="Screenshot 2024-01-04 at 14 12 42" src="https://github.com/gammasim/simtools/assets/50831535/f25e938e-c9d9-4557-bda9-0b82b2fe802d">

Github seems to be complaining about lines not tested which are not related to the PRs being worked on. We should add tests for these lines or add a comment that these lines should be ignored

**Comment by orelgueta** [comment]
> We should add tests for these lines or add a comment that these lines should be ignored

Those lines should not be ignored. We should write tests for them.

**Comment by VictorBarbosaMartins** [comment]
> > We should add tests for these lines or add a comment that these lines should be ignored
> 
> Those lines should not be ignored. We should write tests for them.

Sure, I will take care of that
