### ISSUE TITLE
Altitude vs CORSIKA obs level

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#776]
This is a follow up of the discussions in today's:

- `altitude`: is the altitude of the array center
- `obslevel`: is the observation level used as CORSIKA parameter (`OBSLEV` in the CORSIKA input card)

`obslevel` cannot be negative, so if there is a telescope position lower than the array centre (`altitude`), `obslevel` will be that lower point (we usually round the value in this case).

If we agree on this, then:

- [this description](https://github.com/gammasim/workflows/blob/1777194a1bf4ed17b4626f839f26523d8682278d/schemas/altitude.schema.yml#L9) is wrong: telescope z positions are defined relative to `OBSLEV` and not relative to `altitude`.
- [this line](https://github.com/gammasim/simtools/blob/00472a0155248866a1b2d87ee99c1bee5805f4ce/simtools/applications/make_regular_arrays.py#L94) is wrong: `corsika_telescope_data[site]["corsika_obs_level"] = layout_center_data[site]["center_alt"]`.

**Comment by GernotMaier** [comment]
I have removed the suggestion on parameter names; this is replaced by the discussion in this issue: https://github.com/gammasim/simulation_model/issues/7

**Comment by orelgueta** [comment]
Agree with all you said, except that I think this sentence: 

> `obslevel` cannot be negative

should actually be "a telescope height cannot be negative"

**Comment by GernotMaier** [comment]
You are right, my description on the negative `obslevel` is not entirely correct.

Looking into the corsika manual, this is actually confusing:

- the parameter description for `OSBLEV` requires it to be `>=0`
- the footnote says `For atmospheric models 1 ≤ MODATM ≤ 9 and MODATM ≥ 17 limits are: −1.E5 < OBSLEV(i) < 112.8E5`. So negative values seem to be allowed. 

Anyone, not important for us, our telescopes are on the mountain.

**Comment by GernotMaier** [comment]
Implemented with #761
