### ISSUE TITLE
Add bidict as new dependency for bi-directional mapping

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#781]
I would like to suggest to add [bidict](https://bidict.readthedocs.io/en/main/) as a new dependency (tiny package with 33kb)

This is for the updates of the parameter names, where it would be very useful to easily map in both directions the parameter names.

e.g.,  in a list of site parameter like the following:

```
site_parameters = {
     "altitude": "reference_point_altitude",
    "ref_lon": "reference_point_longitude",
    "ref_lat": "reference_point_latitude",
    "corsika_obs_level": "corsika_observation_level",
 }
```

I would like to make the mapping `corsika_obs_level` -> `corsika_observation_level` and `corsika_observation_level` -> `corsika_obs_level`

With bidict, this would be:

```
site_parameters = bidict({
     "altitude": "reference_point_altitude",
    "ref_lon": "reference_point_longitude",
    "ref_lat": "reference_point_latitude",
    "corsika_obs_level": "corsika_observation_level",
 })
```

And we can call:
```
>>> site_parameters["altitude"]
'reference_point_altitude'
>>> site_parameters.inverse['reference_point_altitude']
'altitude'
```

Don't think this is a critical dependency (could write the code also on my own), simply easy to use.

Final point that this might be temporary: at some point we will have sorted out the naming and updated all collections at the DB. This will simplify the naming then significantly.

**Comment by VictorBarbosaMartins** [comment]
That is an interesting package, but I was expecting one wouldn't need the `.inverse` part and we would be able to call both direction the same way:
```
>>> site_parameters["altitude"]
'reference_point_altitude'
>>> site_parameters'reference_point_altitude']
'altitude'
```
Anyways, I don't have a strong opinion on this, I think we could do it.

**Comment by GernotMaier** [comment]
Thanks for the feedback. I think I have found another solution where I don't need both directions anymore. So closing this one.
