### ISSUE TITLE
Change plotting background for wavelengths larger than  700nm for camera efficiency plots

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#83]
Works very nicely.

Should think about how to indicate in the plot that the qe values are only available up to 700 nm. I first was surprised to see the cut off and was trying to understand it. Maybe some background colouring of the region for which no values are available?

![validate_camera_efficiency_North-MST-NectarCam-D_nsb](https://user-images.githubusercontent.com/14001688/95293054-04d10300-0873-11eb-9c20-36a29ce5f751.png)

**Comment by orelgueta** [comment]
Not sure, do you think it's really necessary? 
I agree it's a little confusing when you first see the plot, but after thinking about it a bit I guess it becomes clearer. I don't mind adding it of course, I just think it might add complication to a plot which is already busy on the one hand and is not used/seen much anyway on the other. In addition, it might look weird for the SiPM cameras when the QE goes all the way to 1000 nm.

**Comment by GernotMaier** [comment]
Why not simply change the background of the plot after 700nm? That indicates to the viewer that something is happening.

**Comment by orelgueta** [comment]
OK, will give it a try to see how it looks (low priority though).

**Comment by GernotMaier** [comment]
I think after 4 years, I am convinced that we can survive without the gray background. Therefore closing this issue.
