### ISSUE TITLE
prod5 parameters not available for simulation

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#874]
I am running the simulation production tool for Prod5 and am getting an error for missing parameter. Perhaps we still need to add the corsika parameters to the DB with the previous versions after we have switched from the corsika parameters file to the DB.

Running:
```
simtools-simulate-prod --production_config tests/resources/prod_multi_config_test.yml --model_version Prod5 --site north --primary gamma --azimuth_angle north --zenith_angle 20 --start_run 0 --run 1
```

Error:
```
simtools.model.model_parameter.InvalidModelParameter: Parameter corsika_observation_level was not found in the model
```

**Comment by GernotMaier** [comment]
This is covered by #851 - I am closing this issue therefore.
