### ISSUE TITLE
Updates on how to handel design models with respect to parameter relevant for individual telescopes

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#879]
We currently have two options on how to get the model parameters for a given telescopes:

- all model parameters are given explicitly in the data base  (e.g., LSTN-01)
- model parameters are given for a design telescopes (e.g., MSTS-design stands for all telescopes).

At this point either all parameters have to be given explicitly or none at all. This is not very efficient if a telescope has differences in a single model parameter in comparison with the design model. 

Suggestion is the change the reading of the model to:

- read first the design model
- update the design model with the parameters found in the database for the telescope in question.

Let me know if there are any worries with this approach.

**Comment by VictorBarbosaMartins** [comment]
agree with your proposal.
