### ISSUE TITLE
Investigate duplicate entries in DB.

### ISSUE THREAD

**Issue by tobiaskleiner** [gammasim/simtools#880]
I noticed that there was no alert when uploading two identical json files to the DB via `add_value_from_json_to_db`. The file in question is the `photons_per_run.json`, which was uploaded to the `calibration_devices` collection.
This should be avoided by simtools validator.

**Comment by GernotMaier** [comment]
I think I misunderstood the issue first - this is actually a feature of the DB wand we want to keep this. We can (and want) upload the same model parameters. While reading, we always get the newest one.

This means that if you want to correct an entry, you just upload a new one.

**Comment by tobiaskleiner** [comment]
Ok thanks, then I will close the issue.
