### ISSUE TITLE
Check reference to schema directory how schema files are included in simtools

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#899]
Schema files are non-python data files and should possibly included following https://setuptools.pypa.io/en/latest/userguide/datafiles.html .

Also the URL access should only be the last option to read schemas (see [this comment](https://github.com/gammasim/simtools/pull/898/files/07c5658da0dc088bb0d5b28b2e6d0f7129f0525f#diff-fc90efc6c32e119c5c145df204dea6f1f5e27d773f82af6f6949a18635b474b9)).

**Comment by VictorBarbosaMartins** [comment]
Copying also my last comment from #898: I think the solution with an env variable for schema_path in the configurator would be a better option (no need for further packages).
