### ISSUE TITLE
Usage of UnitsError from astropy.coordinates.errors

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#908]
This is related to #794 -  tools are simply painfully slow in their startup time and I struggle to accept this. As I have learned is start up == import time.

I would like to point out the costs of using

```
from astropy.coordinates.errors import UnitsError
```

e.g. in geometry.py, this leads to the import of the full astropy.coordinates package with a lot of sub modules and makes up 99% of the required import time for geometry.py.

It is used in this context:

```
   if all(isinstance(variable, (u.Quantity)) for variable in [x, y]):
        if not isinstance(x[0].unit, type(y[0].unit)):
            raise UnitsError(
                "Cannot perform coordinate transformation when x and y have different units."
            )
```

Maybe a ValueError or TypeError would do the same? Or an exception defined at the top of geometry.py? 

(there are a couple of other modules where we use UnitsError.

**Comment by kosack** [comment]
You also should be importing that as `from astropy.units import UnitsError`, and then you don't need to pull in the whole `astropy.coordinates` module, which is very slow to import as it creates the graph of coordinate transforms on the fly.

**Comment by GernotMaier** [comment]
Thanks - this might the issue! 

Is there a trick to find / spot this issues? We have tools which need 2-3 seconds before anything happens, which is a bit slow for the typical usage.

**Comment by kosack** [comment]
> Is there a trick to find / spot this issues? We have tools which need 2-3 seconds before anything happens, which is a bit slow for the typical usage.

I think there is a way to get a import time profile, but generally I just look at which top-level modules are imported.  If you are not using astropy.coordinates functionality, try not to import anything in it.  Though it's hard to tell which modules do a lot of computattion on import.  I know at least `astropy.coordinates` and `astropy.units` both do a lot of setup on the first import.

**Comment by kosack** [comment]
And yes, python import time can be very annoying. We have the same problem for `ctapipe-process` for example, which takes a few seconds before it responds even if you are only doing `--help`. There are some ways around it with lazy loading, but we haven't really tried to optimize yet.  

Note that I have the same issue with the HESS C++/ROOT code, which imports like 50+ shared objects, and it takes 3-5 seconds for a command-line executable to do anything.  So it's a sort of general problem when you have lots of modules to connect.

**Comment by GernotMaier** [comment]
Good - using `from astropy.units import UnitsError` speeds up the startup from 2 s to 1.2s (the rest is mostly pyproj and astropy.units in this case, which is hard to reduce).

Thanks!
