### ISSUE TITLE
Set or save random seed?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#91]
Running the derive_mirror_rnda application a few times, I noticed that the results change slightly every time I run it. I assume this is due to a different random seed each time. Should we try to save or set this this random seed so results can be reproduced exactly?

**Comment by RaulRPrado** [comment]
I'm not sure if sim_telarray allows us to do that. I need to check.
Also, I don't think it's necessary. We should only make sure we are simulating a sufficient number of photons so that these fluctuations are negligible.

**Comment by orelgueta** [comment]
Generally it must be possible in sim_telarray and we have to be able to do it when we run productions. It may not be true for derive_mirror_rnda, but I didn't mean for this issue to be only for that application. I would say that it should be added to any application where it's possible.

**Comment by RaulRPrado** [comment]
Ok, right. I'm trying to find out how to do that.

**Comment by orelgueta** [comment]
Not urgent of course! It's definitely low priority.

**Comment by GernotMaier** [comment]
Orel said everything: seeds should be saved as part of the provenance information to allow for exact reproducibility. This is certainly more important for some than for other use cases.

**Comment by GernotMaier** [comment]
Generally agreement that this is covered by other issues.
