### ISSUE TITLE
simtools-plot-simtel-histograms - cannot found application

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#978]
I have wrongly renamed `simtools-plot-simtel-histograms` in pyproject.toml:

https://github.com/gammasim/simtools/blob/43ae3339fcb6b9cf557fd0a02417b691778780cc/pyproject.toml#L83

But where is this application? I cannot find it in the application directory. @VictorBarbosaMartins ?

**Comment by GernotMaier** [comment]
Or is this `generate_simtel_array_histograms.py` and we need to remove the pyproject.toml entry?

**Comment by VictorBarbosaMartins** [comment]
Hi @GernotMaier, this is a remanent from a previous implementation. The plotting is done now in `generate_simtel_array_histograms.py` as you pointed out. I am then removing this from pyproject
