### ISSUE TITLE
Calculation of adjacent pixels

### ISSUE THREAD

**Issue by tobiaskleiner** [gammasim/simtools#986]
There is an unused section in `_find_adjacent_neighbour_pixels` in `camera.py`.
Discuss if this can be removed or if should be updated.

[`part`](https://github.com/gammasim/simtools/blob/56adc9b1fbef4af51b184f7e0c3b4b6e289e700f/simtools/model/camera.py#L363)

**Comment by GernotMaier** [comment]
@tobiaskleiner - could you give a couple of more details on which section is unused? 

If there is unused code here, please discuss with @orelgueta and remove it if not needed.

**Comment by tobiaskleiner** [comment]
I think we can close this one - can't see any code that is not used. This was probably already removed during the refactoring.

**Comment by GernotMaier** [comment]
Great - closing it.
