### ISSUE TITLE
Replace outdated telescope names (e.g., MST-Structure) by updated CTA nomenclature)

### ISSUE THREAD

**Issue by tobiaskleiner** [gammasim/simtools#993]

**Comment by GernotMaier** [comment]
@tobiaskleiner - I try to address this in PR #1089 , but I have a hard time to find old names in the code. Could you help me if I missed something?

**Comment by tobiaskleiner** [comment]
@GernotMaier I can't find more than the few MST-Structure appearances. I think we removed the others in the past few weeks.

**Comment by GernotMaier** [comment]
Where?!?

**Comment by tobiaskleiner** [comment]
In `mark_non_optics_parameters_non_applicable`

**Comment by GernotMaier** [comment]
This application hopefully goes, see issue #1094 . I therefore don't think we need to put work into it.

This means PR #1089 is ready for review.
